-- 018_anatomy_functions.sql — Body Functions library + region relations + circuits
-- Backs PACK F (Body Functions tool) and PACK B9 (region relations / named circuits).
-- All idempotent. NB: the migrate runner splits on semicolons and strips line
-- comments, so seed strings must contain no semicolons and no double-dash.

CREATE TABLE IF NOT EXISTS anatomy_circuits (
  id SERIAL PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  name_en TEXT NOT NULL,
  name_ru TEXT,
  name_es TEXT,
  description_en TEXT,
  description_ru TEXT,
  description_es TEXT,
  region_ids TEXT[] NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS anatomy_region_relations (
  id SERIAL PRIMARY KEY,
  region_a TEXT NOT NULL,
  region_b TEXT NOT NULL,
  relation_type TEXT NOT NULL DEFAULT 'functional',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (region_a, region_b, relation_type)
);

CREATE TABLE IF NOT EXISTS anatomy_functions (
  id SERIAL PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  name_en TEXT NOT NULL,
  name_ru TEXT,
  name_es TEXT,
  description_en TEXT NOT NULL,
  description_ru TEXT,
  description_es TEXT,
  category TEXT,
  region_ids TEXT[] NOT NULL DEFAULT '{}',
  circuit_ids INTEGER[] DEFAULT '{}',
  tags TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_anatomy_functions_slug ON anatomy_functions(slug);
CREATE INDEX IF NOT EXISTS idx_anatomy_functions_tags ON anatomy_functions USING GIN(tags);
CREATE INDEX IF NOT EXISTS idx_anatomy_functions_cat ON anatomy_functions(category);
CREATE INDEX IF NOT EXISTS idx_anatomy_circuits_slug ON anatomy_circuits(slug);

-- ── named circuits ──────────────────────────────────────────────────────────
INSERT INTO anatomy_circuits (slug, name_en, name_ru, name_es, description_en, description_ru, description_es, region_ids) VALUES
  ('default-mode', 'Default Mode Network', 'Сеть пассивного режима', 'Red neuronal por defecto', 'Active during rest, self-reflection and mind-wandering.', 'Активна в покое, при саморефлексии и блуждании мысли.', 'Activa en reposo, autorreflexion y divagacion mental.', '{frontal-lobe,parietal-lobe,cingulate,hippocampus,temporal-lobe}'),
  ('salience', 'Salience Network', 'Сеть значимости', 'Red de relevancia', 'Detects salient stimuli and switches between brain networks.', 'Выделяет значимые стимулы и переключает сети мозга.', 'Detecta estimulos relevantes y alterna entre redes.', '{insula,cingulate,amygdala}'),
  ('executive-control', 'Executive Control Network', 'Сеть исполнительного контроля', 'Red de control ejecutivo', 'Goal-directed attention, working memory and planning.', 'Целенаправленное внимание, рабочая память и планирование.', 'Atencion dirigida, memoria de trabajo y planificacion.', '{frontal-lobe,parietal-lobe}'),
  ('reward-dopaminergic', 'Reward / Dopaminergic Circuit', 'Дофаминергический контур вознаграждения', 'Circuito dopaminergico de recompensa', 'Motivation, reward learning and reinforcement.', 'Мотивация, обучение на вознаграждении и подкрепление.', 'Motivacion, aprendizaje por recompensa y refuerzo.', '{basal-ganglia,midbrain,frontal-lobe,hypothalamus}'),
  ('memory-hippocampal', 'Memory / Hippocampal Circuit', 'Гиппокампальный контур памяти', 'Circuito hipocampal de memoria', 'Encoding and retrieval of episodic memory.', 'Кодирование и извлечение эпизодической памяти.', 'Codificacion y recuperacion de la memoria episodica.', '{hippocampus,fornix,thalamus,cingulate}'),
  ('motor', 'Motor Circuit', 'Двигательный контур', 'Circuito motor', 'Planning, initiation and coordination of movement.', 'Планирование, запуск и координация движения.', 'Planificacion, inicio y coordinacion del movimiento.', '{frontal-lobe,basal-ganglia,cerebellum,thalamus,spinal-cord}')
ON CONFLICT (slug) DO NOTHING;

-- ── region relations ────────────────────────────────────────────────────────
INSERT INTO anatomy_region_relations (region_a, region_b, relation_type) VALUES
  ('frontal-lobe', 'basal-ganglia', 'functional'),
  ('frontal-lobe', 'parietal-lobe', 'functional'),
  ('frontal-lobe', 'thalamus', 'projection'),
  ('frontal-lobe', 'corpus-callosum', 'structural'),
  ('hippocampus', 'fornix', 'structural'),
  ('hippocampus', 'amygdala', 'functional'),
  ('amygdala', 'hypothalamus', 'projection'),
  ('insula', 'cingulate', 'functional'),
  ('cerebellum', 'thalamus', 'projection'),
  ('midbrain', 'basal-ganglia', 'projection'),
  ('thalamus', 'parietal-lobe', 'projection'),
  ('occipital-lobe', 'temporal-lobe', 'functional')
ON CONFLICT (region_a, region_b, relation_type) DO NOTHING;

-- ── functions library ───────────────────────────────────────────────────────
INSERT INTO anatomy_functions (slug, name_en, name_ru, name_es, description_en, description_ru, description_es, category, region_ids, tags) VALUES
  ('attention', 'Attention', 'Внимание', 'Atencion', 'Selecting and sustaining focus on relevant information.', 'Выбор и удержание фокуса на значимой информации.', 'Seleccion y mantenimiento del foco en informacion relevante.', 'cognitive', '{frontal-lobe,parietal-lobe,cingulate,thalamus}', '{focus,concentration,vnimanie}'),
  ('working-memory', 'Working memory', 'Рабочая память', 'Memoria de trabajo', 'Holding and manipulating information over seconds.', 'Удержание и обработка информации в течение секунд.', 'Mantener y manipular informacion durante segundos.', 'executive', '{frontal-lobe,parietal-lobe}', '{memory,executive}'),
  ('memory-recall', 'Memory recall', 'Воспоминание', 'Recuerdo', 'Retrieving stored episodic and semantic memories.', 'Извлечение сохранённых эпизодических и семантических воспоминаний.', 'Recuperacion de recuerdos episodicos y semanticos.', 'cognitive', '{hippocampus,fornix,frontal-lobe,temporal-lobe}', '{memory,recall}'),
  ('decision-making', 'Decision making', 'Принятие решений', 'Toma de decisiones', 'Weighing options and choosing a course of action.', 'Взвешивание вариантов и выбор действия.', 'Evaluar opciones y elegir una accion.', 'cognitive', '{frontal-lobe,basal-ganglia,cingulate}', '{decision,choice}'),
  ('planning', 'Planning', 'Планирование', 'Planificacion', 'Sequencing actions toward a future goal.', 'Выстраивание последовательности действий к цели.', 'Secuenciar acciones hacia un objetivo.', 'cognitive', '{frontal-lobe,parietal-lobe,cerebellum}', '{planning,executive}'),
  ('mental-imagery', 'Mental imagery', 'Мысленные образы', 'Imagineria mental', 'Generating and manipulating images in the mind.', 'Создание и преобразование образов в уме.', 'Generar y manipular imagenes en la mente.', 'cognitive', '{occipital-lobe,parietal-lobe,frontal-lobe}', '{imagery,visualization}'),
  ('learning', 'Learning', 'Обучение', 'Aprendizaje', 'Acquiring new knowledge and skills over time.', 'Приобретение новых знаний и навыков со временем.', 'Adquisicion de conocimientos y habilidades.', 'cognitive', '{hippocampus,basal-ganglia,cerebellum,frontal-lobe}', '{learning,plasticity}'),
  ('walking', 'Walking', 'Ходьба', 'Caminar', 'Rhythmic locomotion driven by motor and balance systems.', 'Ритмичная локомоция через двигательную систему и баланс.', 'Locomocion ritmica por los sistemas motor y de equilibrio.', 'motor', '{frontal-lobe,basal-ganglia,cerebellum,spinal-cord,thalamus}', '{gait,locomotion,movement}'),
  ('running', 'Running', 'Бег', 'Correr', 'High-intensity locomotion with strong motor and cardiac demand.', 'Высокоинтенсивная локомоция с большой нагрузкой на моторику и сердце.', 'Locomocion de alta intensidad con gran demanda motora y cardiaca.', 'motor', '{frontal-lobe,basal-ganglia,cerebellum,spinal-cord,medulla}', '{running,locomotion,cardio}'),
  ('fine-motor', 'Fine motor control', 'Тонкая моторика', 'Motricidad fina', 'Precise coordinated movements of hands and fingers.', 'Точные согласованные движения кистей и пальцев.', 'Movimientos precisos de manos y dedos.', 'motor', '{frontal-lobe,cerebellum,basal-ganglia,thalamus}', '{dexterity,hands}'),
  ('tongue-motor', 'Tongue movement', 'Движение языка', 'Movimiento de la lengua', 'Motor control of the tongue for speech and swallowing.', 'Моторный контроль языка для речи и глотания.', 'Control motor de la lengua para el habla y la deglucion.', 'motor', '{frontal-lobe,medulla,pons}', '{tongue,speech,oral}'),
  ('eye-movement', 'Eye movement', 'Движение глаз', 'Movimiento ocular', 'Saccades and smooth pursuit that aim the gaze.', 'Саккады и плавное слежение, направляющие взгляд.', 'Sacadas y seguimiento suave que dirigen la mirada.', 'motor', '{frontal-lobe,midbrain,cerebellum,occipital-lobe}', '{gaze,saccade,oculomotor}'),
  ('balance', 'Balance', 'Равновесие', 'Equilibrio', 'Maintaining postural stability against gravity.', 'Поддержание устойчивости позы против силы тяжести.', 'Mantener la estabilidad postural frente a la gravedad.', 'motor', '{cerebellum,pons,thalamus}', '{balance,vestibular}'),
  ('posture', 'Posture', 'Осанка', 'Postura', 'Sustained muscle tone that holds body alignment.', 'Поддерживающий тонус мышц, удерживающий тело.', 'Tono muscular que mantiene la alineacion del cuerpo.', 'motor', '{cerebellum,spinal-cord,basal-ganglia}', '{posture,tone}'),
  ('swallowing', 'Swallowing', 'Глотание', 'Deglucion', 'Coordinated reflex moving food from mouth to stomach.', 'Координированный рефлекс, проводящий пищу в желудок.', 'Reflejo coordinado que lleva el alimento al estomago.', 'motor', '{medulla,pons}', '{swallow,deglutition}'),
  ('vision', 'Vision', 'Зрение', 'Vision', 'Processing light into perceived images.', 'Преобразование света в воспринимаемые образы.', 'Procesar la luz en imagenes percibidas.', 'sensory', '{occipital-lobe,thalamus}', '{sight,visual}'),
  ('hearing', 'Hearing', 'Слух', 'Audicion', 'Processing sound into perceived tones and speech.', 'Преобразование звука в тоны и речь.', 'Procesar el sonido en tonos y habla.', 'sensory', '{temporal-lobe,thalamus,midbrain}', '{auditory,sound}'),
  ('touch', 'Touch', 'Осязание', 'Tacto', 'Sensing pressure, texture and vibration on the skin.', 'Восприятие давления, текстуры и вибрации кожей.', 'Percepcion de presion, textura y vibracion en la piel.', 'sensory', '{parietal-lobe,thalamus,spinal-cord}', '{tactile,somatosensory}'),
  ('proprioception', 'Proprioception', 'Проприоцепция', 'Propiocepcion', 'Sensing the position and motion of the body.', 'Ощущение положения и движения тела.', 'Percepcion de la posicion y el movimiento del cuerpo.', 'sensory', '{cerebellum,parietal-lobe,spinal-cord}', '{body-sense,kinesthesia}'),
  ('smell', 'Smell', 'Обоняние', 'Olfato', 'Detecting and identifying airborne chemicals.', 'Обнаружение и распознавание запахов.', 'Deteccion e identificacion de olores.', 'sensory', '{temporal-lobe,frontal-lobe}', '{olfaction,smell}'),
  ('taste', 'Taste', 'Вкус', 'Gusto', 'Detecting sweet, salty, sour, bitter and umami.', 'Распознавание сладкого, солёного, кислого, горького и умами.', 'Deteccion de dulce, salado, acido, amargo y umami.', 'sensory', '{insula,thalamus}', '{gustation,taste}'),
  ('pain', 'Pain perception', 'Восприятие боли', 'Percepcion del dolor', 'Detecting and interpreting noxious stimuli.', 'Обнаружение и интерпретация повреждающих стимулов.', 'Deteccion e interpretacion de estimulos nocivos.', 'sensory', '{thalamus,insula,cingulate,spinal-cord}', '{pain,nociception}'),
  ('heart-rate', 'Heart rate control', 'Регуляция пульса', 'Control del ritmo cardiaco', 'Autonomic regulation of the heartbeat.', 'Вегетативная регуляция сердечного ритма.', 'Regulacion autonoma del latido cardiaco.', 'autonomic', '{medulla,hypothalamus,heart}', '{heart,autonomic,pulse}'),
  ('breathing', 'Breathing', 'Дыхание', 'Respiracion', 'Automatic rhythmic control of ventilation.', 'Автоматическая ритмичная регуляция дыхания.', 'Control ritmico automatico de la ventilacion.', 'autonomic', '{medulla,pons,lungs}', '{respiration,breath}'),
  ('blood-pressure', 'Blood pressure control', 'Регуляция давления', 'Control de la presion arterial', 'Autonomic regulation of vascular tone and pressure.', 'Вегетативная регуляция тонуса сосудов и давления.', 'Regulacion autonoma del tono vascular y la presion.', 'autonomic', '{medulla,hypothalamus,heart}', '{baroreflex,autonomic}'),
  ('digestion', 'Digestion', 'Пищеварение', 'Digestion', 'Autonomic control of gut motility and secretion.', 'Вегетативная регуляция моторики и секреции ЖКТ.', 'Control autonomo de la motilidad y secrecion intestinal.', 'autonomic', '{medulla,hypothalamus,liver}', '{gut,digestion,autonomic}'),
  ('sleep-wake', 'Sleep and wakefulness', 'Сон и бодрствование', 'Sueno y vigilia', 'Cycling between sleep and alert states.', 'Чередование сна и бодрствования.', 'Alternancia entre el sueno y la vigilia.', 'autonomic', '{hypothalamus,thalamus,pons,midbrain}', '{sleep,arousal,circadian}'),
  ('thermoregulation', 'Thermoregulation', 'Терморегуляция', 'Termorregulacion', 'Maintaining stable core body temperature.', 'Поддержание стабильной температуры тела.', 'Mantener una temperatura corporal estable.', 'autonomic', '{hypothalamus}', '{temperature,homeostasis}'),
  ('fear', 'Fear', 'Страх', 'Miedo', 'Rapid threat detection and defensive response.', 'Быстрое обнаружение угрозы и защитная реакция.', 'Deteccion rapida de amenazas y respuesta defensiva.', 'emotional', '{amygdala,hypothalamus,insula}', '{fear,threat,emotion}'),
  ('joy', 'Joy', 'Радость', 'Alegria', 'Positive affect linked to reward and approach.', 'Положительный аффект, связанный с вознаграждением.', 'Afecto positivo ligado a la recompensa.', 'emotional', '{basal-ganglia,frontal-lobe,midbrain}', '{joy,positive,emotion}'),
  ('empathy', 'Empathy', 'Эмпатия', 'Empatia', 'Sensing and sharing the emotional states of others.', 'Восприятие и разделение эмоций других.', 'Percibir y compartir los estados emocionales de otros.', 'emotional', '{insula,cingulate,frontal-lobe}', '{empathy,social,emotion}'),
  ('reward-processing', 'Reward processing', 'Обработка вознаграждения', 'Procesamiento de recompensa', 'Valuing outcomes and reinforcing behavior.', 'Оценка результатов и подкрепление поведения.', 'Valorar resultados y reforzar la conducta.', 'emotional', '{basal-ganglia,midbrain,frontal-lobe,hypothalamus}', '{reward,dopamine,motivation}'),
  ('stress-response', 'Stress response', 'Реакция на стресс', 'Respuesta al estres', 'Mobilizing the body under perceived demand.', 'Мобилизация организма при ощущаемой нагрузке.', 'Movilizacion del cuerpo ante la demanda percibida.', 'emotional', '{amygdala,hypothalamus,hippocampus}', '{stress,hpa,emotion}'),
  ('speech-production', 'Speech production', 'Производство речи', 'Produccion del habla', 'Planning and articulating spoken language.', 'Планирование и артикуляция устной речи.', 'Planificacion y articulacion del lenguaje hablado.', 'language', '{frontal-lobe,basal-ganglia,cerebellum}', '{speech,broca,language}'),
  ('language-comprehension', 'Language comprehension', 'Понимание речи', 'Comprension del lenguaje', 'Decoding meaning from spoken and written language.', 'Извлечение смысла из устной и письменной речи.', 'Decodificar el significado del lenguaje hablado y escrito.', 'language', '{temporal-lobe,parietal-lobe,frontal-lobe}', '{wernicke,language,comprehension}'),
  ('reading', 'Reading', 'Чтение', 'Lectura', 'Mapping written symbols to language and meaning.', 'Сопоставление письменных символов с языком и смыслом.', 'Asociar simbolos escritos con lenguaje y significado.', 'language', '{occipital-lobe,temporal-lobe,frontal-lobe}', '{reading,literacy,language}'),
  ('inhibition', 'Response inhibition', 'Торможение реакции', 'Inhibicion de respuesta', 'Suppressing inappropriate or automatic responses.', 'Подавление неуместных или автоматических реакций.', 'Suprimir respuestas inapropiadas o automaticas.', 'executive', '{frontal-lobe,basal-ganglia}', '{inhibition,control,executive}'),
  ('task-switching', 'Task switching', 'Переключение задач', 'Cambio de tarea', 'Shifting flexibly between goals and rules.', 'Гибкое переключение между целями и правилами.', 'Cambiar de forma flexible entre objetivos y reglas.', 'executive', '{frontal-lobe,parietal-lobe,basal-ganglia}', '{switching,flexibility,executive}'),
  ('cognitive-flexibility', 'Cognitive flexibility', 'Когнитивная гибкость', 'Flexibilidad cognitiva', 'Adapting thinking to changing demands.', 'Адаптация мышления к меняющимся условиям.', 'Adaptar el pensamiento a demandas cambiantes.', 'executive', '{frontal-lobe,cingulate,basal-ganglia}', '{flexibility,adaptation,executive}')
ON CONFLICT (slug) DO NOTHING;

-- ── link key functions to circuits (by slug, so it is robust to serial ids) ──
UPDATE anatomy_functions SET circuit_ids = ARRAY(SELECT id FROM anatomy_circuits WHERE slug = 'memory-hippocampal') WHERE slug IN ('memory-recall', 'learning') AND circuit_ids = '{}';
UPDATE anatomy_functions SET circuit_ids = ARRAY(SELECT id FROM anatomy_circuits WHERE slug = 'reward-dopaminergic') WHERE slug IN ('reward-processing', 'joy') AND circuit_ids = '{}';
UPDATE anatomy_functions SET circuit_ids = ARRAY(SELECT id FROM anatomy_circuits WHERE slug = 'executive-control') WHERE slug IN ('working-memory', 'planning', 'task-switching', 'inhibition') AND circuit_ids = '{}';
UPDATE anatomy_functions SET circuit_ids = ARRAY(SELECT id FROM anatomy_circuits WHERE slug = 'salience') WHERE slug IN ('attention', 'fear', 'empathy') AND circuit_ids = '{}';
UPDATE anatomy_functions SET circuit_ids = ARRAY(SELECT id FROM anatomy_circuits WHERE slug = 'motor') WHERE slug IN ('walking', 'running', 'fine-motor', 'posture', 'balance') AND circuit_ids = '{}';
UPDATE anatomy_functions SET circuit_ids = ARRAY(SELECT id FROM anatomy_circuits WHERE slug = 'default-mode') WHERE slug IN ('mental-imagery') AND circuit_ids = '{}';

-- ── conditions / states (internal field, parallel to External Field) ────────
CREATE TABLE IF NOT EXISTS human_conditions (
  id SERIAL PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  name_en TEXT NOT NULL,
  name_ru TEXT,
  name_es TEXT,
  category TEXT,
  description_en TEXT,
  description_ru TEXT,
  description_es TEXT,
  affected_region_ids TEXT[] NOT NULL DEFAULT '{}',
  affected_function_ids INTEGER[] DEFAULT '{}',
  impact_summary_en TEXT,
  impact_summary_ru TEXT,
  impact_summary_es TEXT,
  recommendations_en TEXT,
  recommendations_ru TEXT,
  recommendations_es TEXT,
  is_neurodevelopmental BOOLEAN DEFAULT FALSE,
  severity_default TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_human_conditions_slug ON human_conditions(slug);
CREATE INDEX IF NOT EXISTS idx_human_conditions_cat ON human_conditions(category);

INSERT INTO human_conditions (slug, name_en, name_ru, name_es, category, description_en, description_ru, description_es, affected_region_ids, impact_summary_en, impact_summary_ru, impact_summary_es, recommendations_en, recommendations_ru, recommendations_es, is_neurodevelopmental, severity_default) VALUES
  ('alzheimers', 'Alzheimer disease', 'Болезнь Альцгеймера', 'Enfermedad de Alzheimer', 'neurodegenerative', 'Progressive degeneration that erodes memory and cognition, starting in the medial temporal lobe.', 'Прогрессирующая дегенерация, разрушающая память и познание, начинается в медиальной височной доле.', 'Degeneracion progresiva que erosiona la memoria y la cognicion, comienza en el lobulo temporal medial.', '{hippocampus,temporal-lobe,parietal-lobe,frontal-lobe}', 'Memory, orientation and language decline over years.', 'Память, ориентация и речь ухудшаются годами.', 'La memoria, la orientacion y el lenguaje declinan con los anos.', 'Cognitive engagement, sleep, exercise and medical follow-up.', 'Когнитивная нагрузка, сон, движение и наблюдение врача.', 'Estimulacion cognitiva, sueno, ejercicio y seguimiento medico.', FALSE, 'severe'),
  ('parkinsons', 'Parkinson disease', 'Болезнь Паркинсона', 'Enfermedad de Parkinson', 'neurodegenerative', 'Loss of dopaminergic neurons in the midbrain causing tremor, rigidity and slowness.', 'Гибель дофаминовых нейронов среднего мозга вызывает тремор, ригидность и замедленность.', 'Perdida de neuronas dopaminergicas del mesencefalo que causa temblor, rigidez y lentitud.', '{midbrain,basal-ganglia,frontal-lobe}', 'Movement initiation, balance and fine motor control are impaired.', 'Нарушены запуск движения, баланс и тонкая моторика.', 'Se afectan el inicio del movimiento, el equilibrio y la motricidad fina.', 'Regular movement therapy, balance work and medical care.', 'Регулярная двигательная терапия, работа над балансом, наблюдение.', 'Terapia de movimiento, trabajo de equilibrio y atencion medica.', FALSE, 'moderate'),
  ('lewy-body-dementia', 'Dementia with Lewy bodies', 'Деменция с тельцами Леви', 'Demencia por cuerpos de Lewy', 'neurodegenerative', 'Protein deposits cause fluctuating cognition, visual hallucinations and parkinsonism.', 'Белковые отложения вызывают колеблющееся познание, зрительные галлюцинации и паркинсонизм.', 'Depositos proteicos causan cognicion fluctuante, alucinaciones visuales y parkinsonismo.', '{occipital-lobe,basal-ganglia,frontal-lobe,midbrain}', 'Attention and alertness fluctuate, with vivid visual experiences.', 'Внимание и бодрость колеблются, яркие зрительные образы.', 'La atencion fluctua, con experiencias visuales vividas.', 'Structured routine, safety measures and specialist care.', 'Структурированный режим, меры безопасности, специалист.', 'Rutina estructurada, medidas de seguridad y atencion especializada.', FALSE, 'severe'),
  ('huntingtons', 'Huntington disease', 'Болезнь Гентингтона', 'Enfermedad de Huntington', 'neurodegenerative', 'Inherited degeneration of the striatum producing involuntary movements and cognitive change.', 'Наследственная дегенерация полосатого тела с непроизвольными движениями и когнитивными изменениями.', 'Degeneracion hereditaria del estriado con movimientos involuntarios y cambios cognitivos.', '{basal-ganglia,frontal-lobe}', 'Involuntary movement, mood and executive function are affected.', 'Затронуты непроизвольные движения, настроение и исполнительные функции.', 'Se afectan el movimiento involuntario, el animo y la funcion ejecutiva.', 'Multidisciplinary support and movement management.', 'Мультидисциплинарная поддержка и контроль движений.', 'Apoyo multidisciplinario y manejo del movimiento.', FALSE, 'severe'),
  ('als', 'Amyotrophic lateral sclerosis', 'Боковой амиотрофический склероз', 'Esclerosis lateral amiotrofica', 'neurodegenerative', 'Degeneration of motor neurons in cortex and spinal cord causing progressive weakness.', 'Дегенерация мотонейронов коры и спинного мозга с прогрессирующей слабостью.', 'Degeneracion de motoneuronas en corteza y medula que causa debilidad progresiva.', '{frontal-lobe,spinal-cord,medulla}', 'Voluntary muscle control weakens while sensation is spared.', 'Произвольный контроль мышц слабеет, чувствительность сохранна.', 'El control muscular voluntario se debilita y la sensibilidad se conserva.', 'Assistive devices, respiratory support and multidisciplinary care.', 'Вспомогательные средства, дыхательная поддержка, мультидисциплинарная помощь.', 'Dispositivos de apoyo, soporte respiratorio y atencion multidisciplinaria.', FALSE, 'severe'),
  ('frontotemporal-dementia', 'Frontotemporal dementia', 'Лобно-височная деменция', 'Demencia frontotemporal', 'neurodegenerative', 'Degeneration of frontal and temporal lobes altering behavior, personality and language.', 'Дегенерация лобных и височных долей, меняющая поведение, личность и речь.', 'Degeneracion de lobulos frontal y temporal que altera conducta, personalidad y lenguaje.', '{frontal-lobe,temporal-lobe,insula}', 'Behavior, judgment and language change before memory.', 'Поведение, суждение и речь меняются раньше памяти.', 'La conducta, el juicio y el lenguaje cambian antes que la memoria.', 'Structure, caregiver support and specialist follow-up.', 'Структура, поддержка опекунов, наблюдение специалиста.', 'Estructura, apoyo al cuidador y seguimiento especializado.', FALSE, 'severe'),
  ('autism-spectrum', 'Autism spectrum', 'Расстройство аутистического спектра', 'Espectro autista', 'neurodevelopmental', 'A neurodevelopmental variation in social communication, sensory processing and focused interests.', 'Нейроотличие в социальной коммуникации, обработке сенсорики и устойчивых интересах.', 'Una variacion del neurodesarrollo en comunicacion social, procesamiento sensorial e intereses focalizados.', '{frontal-lobe,temporal-lobe,amygdala,cerebellum,insula}', 'Social, sensory and attentional processing differ from the typical pattern.', 'Социальная, сенсорная и внимательная обработка отличаются от типичной.', 'El procesamiento social, sensorial y atencional difiere del patron tipico.', 'Supportive environment, sensory accommodation and strengths-based approach.', 'Поддерживающая среда, сенсорные адаптации, опора на сильные стороны.', 'Entorno de apoyo, adaptacion sensorial y enfoque en fortalezas.', TRUE, 'variable'),
  ('aspergers', 'Asperger profile', 'Профиль Аспергера', 'Perfil de Asperger', 'neurodevelopmental', 'A profile on the autism spectrum with fluent language and focused interests.', 'Профиль аутистического спектра с беглой речью и сфокусированными интересами.', 'Un perfil del espectro autista con lenguaje fluido e intereses focalizados.', '{frontal-lobe,temporal-lobe,amygdala}', 'Social nuance and flexibility differ while verbal skills are strong.', 'Социальные нюансы и гибкость отличаются при сильной речи.', 'El matiz social y la flexibilidad difieren con habilidades verbales fuertes.', 'Clear communication, predictability and respect for interests.', 'Ясная коммуникация, предсказуемость, уважение к интересам.', 'Comunicacion clara, previsibilidad y respeto por los intereses.', TRUE, 'variable'),
  ('adhd', 'ADHD', 'СДВГ', 'TDAH', 'neurodevelopmental', 'A neurodevelopmental pattern of attention regulation, impulsivity and high drive.', 'Нейроотличие в регуляции внимания, импульсивности и высокой активности.', 'Un patron del neurodesarrollo de regulacion de la atencion, impulsividad y alto impulso.', '{frontal-lobe,basal-ganglia,cingulate}', 'Sustained attention and impulse control vary with interest and context.', 'Устойчивое внимание и контроль импульсов зависят от интереса и контекста.', 'La atencion sostenida y el control de impulsos varian con el interes y el contexto.', 'Structure, movement breaks, external cues and strengths focus.', 'Структура, двигательные паузы, внешние подсказки, сильные стороны.', 'Estructura, pausas de movimiento, senales externas y enfoque en fortalezas.', TRUE, 'variable'),
  ('tourette', 'Tourette syndrome', 'Синдром Туретта', 'Sindrome de Tourette', 'neurodevelopmental', 'A neurodevelopmental condition with motor and vocal tics linked to basal ganglia circuits.', 'Нейроотличие с моторными и вокальными тиками, связанное с контурами базальных ганглиев.', 'Una condicion del neurodesarrollo con tics motores y vocales ligados a los ganglios basales.', '{basal-ganglia,frontal-lobe,thalamus}', 'Tics fluctuate and often ease with engagement and calm.', 'Тики колеблются и часто слабеют при вовлечённости и спокойствии.', 'Los tics fluctuan y suelen disminuir con la implicacion y la calma.', 'Low-stress environment, understanding and tic-aware support.', 'Среда без стресса, понимание, поддержка с учётом тиков.', 'Entorno de bajo estres, comprension y apoyo consciente de los tics.', TRUE, 'mild'),
  ('dyslexia', 'Dyslexia', 'Дислексия', 'Dislexia', 'neurodevelopmental', 'A neurodevelopmental difference in mapping written symbols to sound and meaning.', 'Нейроотличие в сопоставлении письменных символов со звуком и смыслом.', 'Una diferencia del neurodesarrollo en asociar simbolos escritos con sonido y significado.', '{temporal-lobe,parietal-lobe,occipital-lobe}', 'Reading fluency differs while reasoning is typically intact.', 'Беглость чтения отличается при сохранном мышлении.', 'La fluidez lectora difiere y el razonamiento suele estar intacto.', 'Multisensory reading methods and extra time.', 'Мультисенсорные методы чтения и дополнительное время.', 'Metodos de lectura multisensoriales y tiempo extra.', TRUE, 'mild'),
  ('dysgraphia', 'Dysgraphia', 'Дисграфия', 'Disgrafia', 'neurodevelopmental', 'A neurodevelopmental difference affecting written expression and handwriting.', 'Нейроотличие, затрагивающее письменную речь и почерк.', 'Una diferencia del neurodesarrollo que afecta la expresion escrita y la escritura a mano.', '{parietal-lobe,frontal-lobe,cerebellum}', 'Writing mechanics differ while ideas remain rich.', 'Механика письма отличается при богатых идеях.', 'La mecanica de la escritura difiere mientras las ideas siguen siendo ricas.', 'Typing options, scaffolds and reduced handwriting load.', 'Печать, опоры и снижение нагрузки на рукописное письмо.', 'Opciones de escritura digital, andamiajes y menos escritura manual.', TRUE, 'mild'),
  ('depression', 'Depressive disorder', 'Депрессивное расстройство', 'Trastorno depresivo', 'psychiatric', 'A mood condition with persistent low mood, anhedonia and altered drive.', 'Расстройство настроения со стойко сниженным настроением, ангедонией и изменённой активностью.', 'Un trastorno del animo con animo bajo persistente, anhedonia e impulso alterado.', '{frontal-lobe,cingulate,hippocampus,amygdala}', 'Mood, motivation, sleep and concentration are affected.', 'Затронуты настроение, мотивация, сон и концентрация.', 'Se afectan el animo, la motivacion, el sueno y la concentracion.', 'Behavioral activation, sleep, connection and professional support.', 'Поведенческая активация, сон, связь, профессиональная помощь.', 'Activacion conductual, sueno, vinculo y apoyo profesional.', FALSE, 'moderate'),
  ('bipolar', 'Bipolar disorder', 'Биполярное расстройство', 'Trastorno bipolar', 'psychiatric', 'A mood condition cycling between depressive and elevated or manic states.', 'Расстройство настроения с чередованием депрессивных и приподнятых или маниакальных состояний.', 'Un trastorno del animo que alterna entre estados depresivos y elevados o maniacos.', '{frontal-lobe,amygdala,basal-ganglia,cingulate}', 'Energy, mood and judgment shift between phases.', 'Энергия, настроение и суждение меняются между фазами.', 'La energia, el animo y el juicio cambian entre fases.', 'Routine, sleep regularity, mood tracking and care.', 'Режим, регулярный сон, отслеживание настроения, помощь.', 'Rutina, regularidad del sueno, registro del animo y atencion.', FALSE, 'moderate'),
  ('gad', 'Generalized anxiety', 'Генерализованная тревога', 'Ansiedad generalizada', 'psychiatric', 'Persistent excessive worry with bodily tension driven by an overactive threat system.', 'Стойкое чрезмерное беспокойство с телесным напряжением из-за гиперактивной системы тревоги.', 'Preocupacion excesiva persistente con tension corporal por un sistema de amenaza hiperactivo.', '{amygdala,frontal-lobe,insula,hypothalamus}', 'Worry, vigilance and bodily arousal stay elevated.', 'Беспокойство, бдительность и телесное возбуждение повышены.', 'La preocupacion, la vigilancia y la activacion corporal permanecen elevadas.', 'Breathwork, grounding, sleep and graded exposure.', 'Дыхание, заземление, сон, постепенная экспозиция.', 'Respiracion, anclaje, sueno y exposicion gradual.', FALSE, 'moderate'),
  ('ptsd', 'PTSD', 'ПТСР', 'TEPT', 'psychiatric', 'A trauma-linked condition with intrusive memories and heightened threat response.', 'Связанное с травмой состояние с навязчивыми воспоминаниями и усиленной реакцией на угрозу.', 'Una condicion ligada al trauma con recuerdos intrusivos y respuesta de amenaza aumentada.', '{amygdala,hippocampus,frontal-lobe,insula}', 'Threat detection, memory and arousal are dysregulated.', 'Нарушены обнаружение угрозы, память и возбуждение.', 'La deteccion de amenazas, la memoria y la activacion estan desreguladas.', 'Safety, grounding, paced processing and trauma-informed care.', 'Безопасность, заземление, дозированная переработка, травма-информированная помощь.', 'Seguridad, anclaje, procesamiento gradual y atencion sensible al trauma.', FALSE, 'moderate'),
  ('ocd', 'OCD', 'ОКР', 'TOC', 'psychiatric', 'Intrusive thoughts and repetitive behaviors tied to a cortico-striatal loop.', 'Навязчивые мысли и повторяющиеся действия, связанные с кортико-стриарной петлёй.', 'Pensamientos intrusivos y conductas repetitivas ligados a un bucle cortico-estriatal.', '{frontal-lobe,basal-ganglia,cingulate}', 'Intrusive urges and compulsions consume time and energy.', 'Навязчивые позывы и ритуалы отнимают время и силы.', 'Los impulsos intrusivos y las compulsiones consumen tiempo y energia.', 'Exposure with response prevention and professional support.', 'Экспозиция с предотвращением реакции, профессиональная помощь.', 'Exposicion con prevencion de respuesta y apoyo profesional.', FALSE, 'moderate'),
  ('schizophrenia', 'Schizophrenia', 'Шизофрения', 'Esquizofrenia', 'psychiatric', 'A condition altering perception, thought and dopamine signaling across networks.', 'Состояние, меняющее восприятие, мышление и дофаминовую передачу в сетях мозга.', 'Una condicion que altera la percepcion, el pensamiento y la senalizacion dopaminergica.', '{frontal-lobe,temporal-lobe,basal-ganglia,thalamus}', 'Perception, thought organization and motivation are affected.', 'Затронуты восприятие, организация мышления и мотивация.', 'Se afectan la percepcion, la organizacion del pensamiento y la motivacion.', 'Continuity of care, support and structured routine.', 'Непрерывность помощи, поддержка, структурированный режим.', 'Continuidad de la atencion, apoyo y rutina estructurada.', FALSE, 'severe'),
  ('bpd', 'Borderline personality', 'Пограничное расстройство', 'Trastorno limite', 'psychiatric', 'Intense emotion, relationship sensitivity and impulsivity with limbic-prefrontal imbalance.', 'Интенсивные эмоции, чувствительность в отношениях и импульсивность при лимбико-префронтальном дисбалансе.', 'Emocion intensa, sensibilidad relacional e impulsividad con desequilibrio limbico-prefrontal.', '{amygdala,frontal-lobe,cingulate,insula}', 'Emotion regulation and self-image shift rapidly.', 'Регуляция эмоций и образ себя быстро меняются.', 'La regulacion emocional y la autoimagen cambian rapidamente.', 'Skills training, validation and consistent support.', 'Тренинг навыков, валидация, последовательная поддержка.', 'Entrenamiento de habilidades, validacion y apoyo constante.', FALSE, 'moderate'),
  ('gastritis', 'Gastritis', 'Гастрит', 'Gastritis', 'gi', 'Inflammation of the stomach lining causing pain and digestive discomfort.', 'Воспаление слизистой желудка с болью и нарушением пищеварения.', 'Inflamacion del revestimiento del estomago con dolor y molestias digestivas.', '{liver,medulla}', 'Digestion and appetite are disrupted.', 'Нарушены пищеварение и аппетит.', 'Se alteran la digestion y el apetito.', 'Dietary care, stress reduction and medical evaluation.', 'Питание, снижение стресса, обследование.', 'Cuidado dietetico, reduccion del estres y evaluacion medica.', FALSE, 'mild'),
  ('gerd', 'GERD', 'ГЭРБ', 'ERGE', 'gi', 'Acid reflux from the stomach into the esophagus causing heartburn.', 'Заброс кислоты из желудка в пищевод с изжогой.', 'Reflujo acido del estomago al esofago que causa ardor.', '{liver,medulla}', 'Reflux affects comfort, sleep and the throat.', 'Рефлюкс влияет на комфорт, сон и горло.', 'El reflujo afecta el confort, el sueno y la garganta.', 'Meal timing, posture and medical guidance.', 'Время приёма пищи, поза, рекомендации врача.', 'Horario de comidas, postura y orientacion medica.', FALSE, 'mild'),
  ('ibs', 'Irritable bowel syndrome', 'Синдром раздражённого кишечника', 'Sindrome del intestino irritable', 'gi', 'A gut-brain disorder with abdominal pain and altered bowel habits.', 'Расстройство оси кишечник-мозг с болью в животе и изменённым стулом.', 'Un trastorno del eje intestino-cerebro con dolor abdominal y habito intestinal alterado.', '{liver,medulla,insula,hypothalamus}', 'Gut sensitivity and stress reactivity interact.', 'Чувствительность кишечника и реактивность на стресс взаимодействуют.', 'La sensibilidad intestinal y la reactividad al estres interactuan.', 'Gut-directed routine, stress work and diet adjustment.', 'Режим для кишечника, работа со стрессом, коррекция питания.', 'Rutina digestiva, trabajo del estres y ajuste de dieta.', FALSE, 'mild'),
  ('crohns', 'Crohn disease', 'Болезнь Крона', 'Enfermedad de Crohn', 'gi', 'Chronic inflammatory bowel disease affecting the digestive tract.', 'Хроническое воспалительное заболевание кишечника, поражающее ЖКТ.', 'Enfermedad inflamatoria intestinal cronica que afecta el tracto digestivo.', '{liver}', 'Inflammation affects nutrition, energy and comfort.', 'Воспаление влияет на питание, энергию и комфорт.', 'La inflamacion afecta la nutricion, la energia y el confort.', 'Specialist care, nutrition and flare management.', 'Помощь специалиста, питание, контроль обострений.', 'Atencion especializada, nutricion y manejo de brotes.', FALSE, 'moderate'),
  ('cirrhosis', 'Liver cirrhosis', 'Цирроз печени', 'Cirrosis hepatica', 'gi', 'Scarring of the liver that impairs its metabolic and filtering functions.', 'Рубцевание печени, нарушающее её обменные и фильтрующие функции.', 'Cicatrizacion del higado que altera sus funciones metabolicas y de filtrado.', '{liver}', 'Detoxification, metabolism and clotting are impaired.', 'Нарушены детоксикация, метаболизм и свёртывание.', 'Se alteran la desintoxicacion, el metabolismo y la coagulacion.', 'Medical management, nutrition and avoiding toxins.', 'Медицинское ведение, питание, отказ от токсинов.', 'Manejo medico, nutricion y evitar toxinas.', FALSE, 'severe'),
  ('hip-osteoarthritis', 'Hip osteoarthritis', 'Коксартроз', 'Coxartrosis', 'musculoskeletal', 'Wear of the hip joint cartilage causing pain and reduced mobility.', 'Износ хряща тазобедренного сустава с болью и снижением подвижности.', 'Desgaste del cartilago de la cadera con dolor y menor movilidad.', '{sacral-spine,lumbar-spine}', 'Hip mobility and gait are limited.', 'Ограничены подвижность бедра и походка.', 'Se limitan la movilidad de la cadera y la marcha.', 'Strengthening, mobility work and load management.', 'Укрепление, работа над подвижностью, контроль нагрузки.', 'Fortalecimiento, trabajo de movilidad y manejo de carga.', FALSE, 'moderate'),
  ('spinal-osteochondrosis', 'Spinal osteochondrosis', 'Остеохондроз позвоночника', 'Osteocondrosis vertebral', 'musculoskeletal', 'Degenerative change of spinal discs and vertebrae causing back pain and stiffness.', 'Дегенеративные изменения дисков и позвонков с болью в спине и скованностью.', 'Cambio degenerativo de discos y vertebras con dolor de espalda y rigidez.', '{cervical-spine,thoracic-spine,lumbar-spine,spinal-cord}', 'Spinal mobility and comfort decline.', 'Снижаются подвижность позвоночника и комфорт.', 'Disminuyen la movilidad vertebral y el confort.', 'Posture, core strength and movement variety.', 'Осанка, сила кора, разнообразие движения.', 'Postura, fuerza del core y variedad de movimiento.', FALSE, 'mild'),
  ('disc-herniation', 'Disc herniation', 'Грыжа межпозвоночного диска', 'Hernia discal', 'musculoskeletal', 'A displaced spinal disc pressing on nerves causing pain and sometimes weakness.', 'Смещённый межпозвоночный диск давит на нервы, вызывая боль и иногда слабость.', 'Un disco desplazado que comprime nervios y causa dolor y a veces debilidad.', '{lumbar-spine,cervical-spine,spinal-cord}', 'Nerve compression causes pain, numbness or weakness.', 'Сдавление нерва вызывает боль, онемение или слабость.', 'La compresion nerviosa causa dolor, entumecimiento o debilidad.', 'Graded movement, core support and medical guidance.', 'Дозированное движение, поддержка кора, рекомендации врача.', 'Movimiento gradual, apoyo del core y orientacion medica.', FALSE, 'moderate'),
  ('hypertension', 'Hypertension', 'Гипертония', 'Hipertension', 'cardiovascular', 'Chronically elevated blood pressure straining the heart and vessels.', 'Хронически повышенное давление, нагружающее сердце и сосуды.', 'Presion arterial cronicamente elevada que sobrecarga el corazon y los vasos.', '{heart,medulla,kidneys}', 'Vascular load rises, raising long-term risk.', 'Растёт нагрузка на сосуды, повышая отдалённый риск.', 'Aumenta la carga vascular, elevando el riesgo a largo plazo.', 'Movement, sleep, salt awareness and monitoring.', 'Движение, сон, контроль соли, мониторинг.', 'Movimiento, sueno, atencion a la sal y monitoreo.', FALSE, 'moderate'),
  ('coronary-artery-disease', 'Coronary artery disease', 'Ишемическая болезнь сердца', 'Enfermedad coronaria', 'cardiovascular', 'Narrowed coronary arteries reducing blood flow to the heart muscle.', 'Сужение коронарных артерий, снижающее кровоток к сердечной мышце.', 'Arterias coronarias estrechadas que reducen el flujo al musculo cardiaco.', '{heart}', 'Reduced cardiac blood flow limits exertion.', 'Сниженный коронарный кровоток ограничивает нагрузку.', 'El menor flujo cardiaco limita el esfuerzo.', 'Cardio-protective habits and medical care.', 'Кардиопротективные привычки и медицинская помощь.', 'Habitos cardioprotectores y atencion medica.', FALSE, 'moderate'),
  ('heart-failure', 'Heart failure', 'Сердечная недостаточность', 'Insuficiencia cardiaca', 'cardiovascular', 'The heart pumps less effectively, reducing oxygen delivery to the body.', 'Сердце качает менее эффективно, снижая доставку кислорода тканям.', 'El corazon bombea con menos eficacia, reduciendo el aporte de oxigeno.', '{heart,lungs,kidneys}', 'Stamina, fluid balance and breathing are affected.', 'Затронуты выносливость, водный баланс и дыхание.', 'Se afectan la resistencia, el balance de liquidos y la respiracion.', 'Medical management, paced activity and monitoring.', 'Медицинское ведение, дозированная активность, мониторинг.', 'Manejo medico, actividad gradual y monitoreo.', FALSE, 'severe'),
  ('type1-diabetes', 'Type 1 diabetes', 'Диабет 1 типа', 'Diabetes tipo 1', 'endocrine', 'Autoimmune loss of insulin production requiring external insulin.', 'Аутоиммунная потеря выработки инсулина, требующая внешнего инсулина.', 'Perdida autoinmune de la produccion de insulina que requiere insulina externa.', '{hypothalamus,liver}', 'Blood glucose regulation depends on external management.', 'Регуляция глюкозы зависит от внешнего управления.', 'La regulacion de la glucosa depende del manejo externo.', 'Glucose monitoring, insulin and consistent routine.', 'Контроль глюкозы, инсулин, постоянный режим.', 'Monitoreo de glucosa, insulina y rutina constante.', FALSE, 'moderate'),
  ('type2-diabetes', 'Type 2 diabetes', 'Диабет 2 типа', 'Diabetes tipo 2', 'endocrine', 'Insulin resistance and impaired glucose control affecting whole-body metabolism.', 'Инсулинорезистентность и нарушенный контроль глюкозы, влияющие на обмен всего тела.', 'Resistencia a la insulina y control deficiente de la glucosa que afecta el metabolismo.', '{hypothalamus,liver,kidneys}', 'Metabolic regulation and energy are affected.', 'Затронуты метаболическая регуляция и энергия.', 'Se afectan la regulacion metabolica y la energia.', 'Movement, nutrition, sleep and monitoring.', 'Движение, питание, сон, мониторинг.', 'Movimiento, nutricion, sueno y monitoreo.', FALSE, 'moderate'),
  ('hypothyroidism', 'Hypothyroidism', 'Гипотиреоз', 'Hipotiroidismo', 'endocrine', 'Underactive thyroid slowing metabolism, energy and mood.', 'Сниженная функция щитовидной железы замедляет метаболизм, энергию и настроение.', 'Tiroides hipoactiva que ralentiza el metabolismo, la energia y el animo.', '{hypothalamus}', 'Metabolic rate, energy and mood slow down.', 'Замедляются обмен, энергия и настроение.', 'Disminuyen el metabolismo, la energia y el animo.', 'Medical management and steady routine.', 'Медицинское ведение и стабильный режим.', 'Manejo medico y rutina estable.', FALSE, 'mild'),
  ('hyperthyroidism', 'Hyperthyroidism', 'Гипертиреоз', 'Hipertiroidismo', 'endocrine', 'Overactive thyroid speeding metabolism, heart rate and arousal.', 'Повышенная функция щитовидной железы ускоряет метаболизм, пульс и возбуждение.', 'Tiroides hiperactiva que acelera el metabolismo, el pulso y la activacion.', '{hypothalamus,heart}', 'Metabolism and arousal run high.', 'Метаболизм и возбуждение повышены.', 'El metabolismo y la activacion estan elevados.', 'Medical management and rest balance.', 'Медицинское ведение и баланс отдыха.', 'Manejo medico y equilibrio del descanso.', FALSE, 'moderate'),
  ('migraine', 'Migraine', 'Мигрень', 'Migrana', 'neurological', 'Recurrent intense headaches with sensory sensitivity and neural hyperexcitability.', 'Повторяющиеся сильные головные боли с сенсорной чувствительностью и нейронной гипервозбудимостью.', 'Cefaleas intensas recurrentes con sensibilidad sensorial e hiperexcitabilidad neural.', '{occipital-lobe,thalamus,medulla,insula}', 'Pain, light and sound sensitivity disrupt function.', 'Боль, свето- и звукочувствительность нарушают функционирование.', 'El dolor y la sensibilidad a luz y sonido alteran el funcionamiento.', 'Trigger awareness, sleep, hydration and pacing.', 'Знание триггеров, сон, гидратация, дозирование.', 'Conciencia de desencadenantes, sueno, hidratacion y ritmo.', FALSE, 'moderate'),
  ('epilepsy', 'Epilepsy', 'Эпилепсия', 'Epilepsia', 'neurological', 'A tendency toward recurrent seizures from abnormal synchronized neural activity.', 'Склонность к повторяющимся приступам из-за аномальной синхронной нейронной активности.', 'Tendencia a crisis recurrentes por actividad neuronal sincronizada anormal.', '{temporal-lobe,frontal-lobe,hippocampus,thalamus}', 'Seizures transiently disrupt awareness or movement.', 'Приступы временно нарушают сознание или движение.', 'Las crisis alteran temporalmente la conciencia o el movimiento.', 'Sleep, trigger care and consistent medical management.', 'Сон, контроль триггеров, постоянное медицинское ведение.', 'Sueno, cuidado de desencadenantes y manejo medico constante.', FALSE, 'moderate'),
  ('insomnia', 'Insomnia', 'Бессонница', 'Insomnio', 'neurological', 'Persistent difficulty falling or staying asleep with daytime impact.', 'Стойкие трудности засыпания или поддержания сна с дневными последствиями.', 'Dificultad persistente para conciliar o mantener el sueno con impacto diurno.', '{hypothalamus,thalamus,pons,frontal-lobe}', 'Sleep, recovery and daytime focus suffer.', 'Страдают сон, восстановление и дневная концентрация.', 'Se afectan el sueno, la recuperacion y el foco diurno.', 'Sleep hygiene, light timing and wind-down routine.', 'Гигиена сна, режим света, ритуал расслабления.', 'Higiene del sueno, manejo de la luz y rutina de relajacion.', FALSE, 'mild'),
  ('stroke', 'Stroke', 'Инсульт', 'Ictus', 'neurological', 'Interrupted blood flow to the brain causing focal loss of function.', 'Прерывание кровотока к мозгу с очаговой потерей функции.', 'Interrupcion del flujo sanguineo al cerebro con perdida focal de funcion.', '{frontal-lobe,parietal-lobe,temporal-lobe,basal-ganglia}', 'Function loss depends on the affected region.', 'Потеря функции зависит от поражённой области.', 'La perdida de funcion depende de la region afectada.', 'Acute care, rehabilitation and risk reduction.', 'Острая помощь, реабилитация, снижение рисков.', 'Atencion aguda, rehabilitacion y reduccion de riesgo.', FALSE, 'severe'),
  ('multiple-sclerosis', 'Multiple sclerosis', 'Рассеянный склероз', 'Esclerosis multiple', 'neurological', 'Immune-mediated damage to nerve insulation across the brain and spinal cord.', 'Иммунное повреждение оболочки нервов в головном и спинном мозге.', 'Dano inmunomediado a la mielina en el cerebro y la medula.', '{frontal-lobe,cerebellum,spinal-cord,corpus-callosum}', 'Signal speed and coordination vary over time.', 'Скорость передачи сигналов и координация меняются со временем.', 'La velocidad de senal y la coordinacion varian con el tiempo.', 'Energy pacing, movement and specialist care.', 'Дозирование энергии, движение, помощь специалиста.', 'Dosificacion de energia, movimiento y atencion especializada.', FALSE, 'moderate'),
  ('copd', 'COPD', 'ХОБЛ', 'EPOC', 'respiratory', 'Chronic airflow limitation that makes breathing progressively harder.', 'Хроническое ограничение потока воздуха, делающее дыхание всё труднее.', 'Limitacion cronica del flujo aereo que dificulta la respiracion.', '{lungs,medulla}', 'Breathing capacity and stamina decline.', 'Снижаются дыхательная способность и выносливость.', 'Disminuyen la capacidad respiratoria y la resistencia.', 'Breathing work, activity pacing and medical care.', 'Дыхательные практики, дозирование активности, помощь.', 'Trabajo respiratorio, dosificacion de actividad y atencion medica.', FALSE, 'moderate'),
  ('asthma', 'Asthma', 'Астма', 'Asma', 'respiratory', 'Reversible airway narrowing and inflammation triggered by various stimuli.', 'Обратимое сужение и воспаление дыхательных путей от различных стимулов.', 'Estrechamiento e inflamacion reversibles de las vias aereas por diversos estimulos.', '{lungs,medulla}', 'Airway reactivity affects breathing during triggers.', 'Реактивность дыхательных путей влияет на дыхание при триггерах.', 'La reactividad de las vias aereas afecta la respiracion ante desencadenantes.', 'Trigger control, breathing technique and medical plan.', 'Контроль триггеров, дыхательная техника, план лечения.', 'Control de desencadenantes, tecnica respiratoria y plan medico.', FALSE, 'mild'),
  ('allergic-rhinitis', 'Allergic rhinitis', 'Аллергический ринит', 'Rinitis alergica', 'respiratory', 'Immune reaction to airborne allergens causing nasal congestion and irritation.', 'Иммунная реакция на аэроаллергены с заложенностью носа и раздражением.', 'Reaccion inmune a alergenos del aire con congestion nasal e irritacion.', '{lungs}', 'Nasal comfort, sleep and focus can be affected.', 'Могут страдать носовой комфорт, сон и концентрация.', 'Se pueden afectar el confort nasal, el sueno y el foco.', 'Allergen reduction and symptom management.', 'Снижение аллергенов и контроль симптомов.', 'Reduccion de alergenos y manejo de sintomas.', FALSE, 'mild')
ON CONFLICT (slug) DO NOTHING;

-- link a representative set of conditions to functions (by slug, robust to ids)
UPDATE human_conditions SET affected_function_ids = ARRAY(SELECT id FROM anatomy_functions WHERE slug = ANY(ARRAY['memory-recall','learning','attention'])) WHERE slug = 'alzheimers' AND affected_function_ids = '{}';
UPDATE human_conditions SET affected_function_ids = ARRAY(SELECT id FROM anatomy_functions WHERE slug = ANY(ARRAY['walking','fine-motor','balance','posture'])) WHERE slug = 'parkinsons' AND affected_function_ids = '{}';
UPDATE human_conditions SET affected_function_ids = ARRAY(SELECT id FROM anatomy_functions WHERE slug = ANY(ARRAY['attention','inhibition','task-switching','working-memory'])) WHERE slug = 'adhd' AND affected_function_ids = '{}';
UPDATE human_conditions SET affected_function_ids = ARRAY(SELECT id FROM anatomy_functions WHERE slug = ANY(ARRAY['fear','stress-response','memory-recall'])) WHERE slug = 'ptsd' AND affected_function_ids = '{}';
UPDATE human_conditions SET affected_function_ids = ARRAY(SELECT id FROM anatomy_functions WHERE slug = ANY(ARRAY['reading','language-comprehension'])) WHERE slug = 'dyslexia' AND affected_function_ids = '{}';
UPDATE human_conditions SET affected_function_ids = ARRAY(SELECT id FROM anatomy_functions WHERE slug = ANY(ARRAY['empathy','attention','cognitive-flexibility'])) WHERE slug = 'autism-spectrum' AND affected_function_ids = '{}';
UPDATE human_conditions SET affected_function_ids = ARRAY(SELECT id FROM anatomy_functions WHERE slug = ANY(ARRAY['vision','attention'])) WHERE slug = 'migraine' AND affected_function_ids = '{}';
UPDATE human_conditions SET affected_function_ids = ARRAY(SELECT id FROM anatomy_functions WHERE slug = ANY(ARRAY['breathing'])) WHERE slug IN ('copd','asthma') AND affected_function_ids = '{}';
UPDATE human_conditions SET affected_function_ids = ARRAY(SELECT id FROM anatomy_functions WHERE slug = ANY(ARRAY['heart-rate','blood-pressure'])) WHERE slug IN ('hypertension','heart-failure') AND affected_function_ids = '{}';
UPDATE human_conditions SET affected_function_ids = ARRAY(SELECT id FROM anatomy_functions WHERE slug = ANY(ARRAY['sleep-wake'])) WHERE slug = 'insomnia' AND affected_function_ids = '{}';

-- ── unified tool: rename/extend anatomy-atlas -> human-atlas (Human Atlas) ───
-- Single tool with 3 in-app tabs (Anatomy / Human Functions / Conditions).
-- Do NOT create a separate anatomy-functions tool. The id is preserved so any
-- existing course_tools grants keep working.
UPDATE tools SET code = 'human-atlas',
  name_ru = 'Атлас человека', name_en = 'Human Atlas', name_es = 'Atlas humano',
  description_ru = 'Единый 3D-атлас: анатомия, функции человека и состояния.',
  description_en = 'Unified 3D atlas: anatomy, human functions and conditions.',
  description_es = 'Atlas 3D unificado: anatomia, funciones humanas y estados.'
  WHERE code = 'anatomy-atlas';
-- Fresh DBs that never had anatomy-atlas: ensure the tool exists.
INSERT INTO tools (code, name_ru, name_en, name_es, description_ru, description_en, description_es, is_free_default, order_idx) VALUES
  ('human-atlas', 'Атлас человека', 'Human Atlas', 'Atlas humano', 'Единый 3D-атлас: анатомия, функции человека и состояния.', 'Unified 3D atlas: anatomy, human functions and conditions.', 'Atlas 3D unificado: anatomia, funciones humanas y estados.', FALSE, 7)
ON CONFLICT (code) DO NOTHING;
-- Drop a stale standalone anatomy-functions tool if a prior build created one
-- and it is not granted to any course (safe: no data loss).
DELETE FROM tools WHERE code = 'anatomy-functions' AND id NOT IN (SELECT tool_id FROM course_tools);
