-- Migration 023 — Gynecological / pregnancy / lactation conditions (PR #100)
-- Adds female-anatomy medical conditions to human_conditions (Human Atlas → Conditions tab).
-- Uses ONLY region slugs already present in SEED_REGION_INFO (Phase 0 female anatomy):
--   uterus, ovaries, fallopian-tubes, cervix, vagina, breasts, placenta,
--   pancreas, stomach, kidneys, hypothalamus, pituitary, medulla.
-- New category: 'gynecological' (i18n label added in account.html CAT map).
-- Idempotent: ON CONFLICT (slug) DO NOTHING + a region/category refresh below.
-- Mirrored INLINE in POST /api/run-migrations (Railway has no auto-migrate).

INSERT INTO human_conditions (slug, name_en, name_ru, name_es, category, description_en, description_ru, description_es, affected_region_ids, impact_summary_en, impact_summary_ru, impact_summary_es, recommendations_en, recommendations_ru, recommendations_es, is_neurodevelopmental, severity_default) VALUES
  ('endometriosis', 'Endometriosis', 'Эндометриоз', 'Endometriosis', 'gynecological', 'A condition where endometrial-like tissue grows outside the uterus, causing pain and menstrual disruption.', 'Заболевание, при котором эндометрий растёт за пределами полости матки, вызывая боль и нарушения цикла.', 'Una afeccion en la que tejido similar al endometrio crece fuera del utero, causando dolor y alteraciones del ciclo.', '{uterus,ovaries,fallopian-tubes}', 'Pain, inflammation and cycle changes affect wellbeing and fertility.', 'Боль, воспаление и нарушения цикла влияют на самочувствие и фертильность.', 'El dolor, la inflamacion y los cambios del ciclo afectan el bienestar y la fertilidad.', 'Gynecological care, pain management and hormonal therapy when indicated.', 'Наблюдение гинеколога, обезболивание и гормональная терапия по показаниям.', 'Atencion ginecologica, manejo del dolor y terapia hormonal cuando este indicada.', FALSE, 'moderate'),
  ('pcos', 'Polycystic ovary syndrome', 'СПКЯ (синдром поликистозных яичников)', 'Sindrome de ovario poliquistico', 'gynecological', 'An endocrine disorder with multiple ovarian cysts, hormonal imbalance and irregular cycles.', 'Эндокринное расстройство, характеризующееся множественными кистами в яичниках, гормональным дисбалансом и нарушением цикла.', 'Un trastorno endocrino con multiples quistes ovaricos, desequilibrio hormonal y ciclos irregulares.', '{ovaries,hypothalamus,pituitary}', 'Hormonal balance, cycle, metabolism and fertility are affected.', 'Затронуты гормональный баланс, цикл, обмен веществ и фертильность.', 'Se afectan el equilibrio hormonal, el ciclo, el metabolismo y la fertilidad.', 'Nutrition, movement, weight management and endocrine care.', 'Питание, движение, контроль веса и эндокринологическое ведение.', 'Nutricion, movimiento, control del peso y atencion endocrina.', FALSE, 'moderate'),
  ('uterine-fibroids', 'Uterine fibroids', 'Миома матки', 'Miomas uterinos', 'gynecological', 'Benign muscular tumours (fibroids) growing in the uterus.', 'Доброкачественные опухоли (миомы) в матке.', 'Tumores musculares benignos (miomas) que crecen en el utero.', '{uterus}', 'May cause heavy periods, pelvic pressure and discomfort.', 'Возможны обильные менструации, давление в тазу и дискомфорт.', 'Pueden causar menstruaciones abundantes, presion pelvica y molestias.', 'Monitoring, symptom control and treatment when indicated.', 'Наблюдение, контроль симптомов и лечение по показаниям.', 'Seguimiento, control de sintomas y tratamiento cuando este indicado.', FALSE, 'mild'),
  ('cervical-dysplasia', 'Cervical dysplasia', 'Дисплазия шейки матки', 'Displasia cervical', 'gynecological', 'Abnormal development of cervical cells, a precancerous change.', 'Аномальное развитие клеток шейки матки, предраковое состояние.', 'Desarrollo anormal de las celulas del cuello uterino, una condicion precancerosa.', '{cervix}', 'Early detection and follow-up reduce the risk of progression.', 'Раннее выявление и наблюдение снижают риск прогрессирования.', 'La deteccion temprana y el seguimiento reducen el riesgo de progresion.', 'Regular screening (Pap test), follow-up and treatment when indicated.', 'Регулярный скрининг (Пап-тест), наблюдение и лечение по показаниям.', 'Cribado regular (Papanicolaou), seguimiento y tratamiento cuando este indicado.', FALSE, 'moderate'),
  ('vaginitis', 'Vaginitis', 'Вагинит', 'Vaginitis', 'gynecological', 'Inflammation of the vaginal lining, often from infection or irritation.', 'Воспаление слизистой влагалища.', 'Inflamacion de la mucosa vaginal, a menudo por infeccion o irritacion.', '{vagina}', 'Discomfort, itching and discharge affect wellbeing.', 'Дискомфорт, зуд и выделения влияют на самочувствие.', 'Las molestias, el picor y el flujo afectan el bienestar.', 'Hygiene, identifying the cause and treatment as prescribed.', 'Гигиена, выявление причины и лечение по назначению врача.', 'Higiene, identificacion de la causa y tratamiento segun indicacion.', FALSE, 'mild'),
  ('gestational-diabetes', 'Gestational diabetes', 'Гестационный диабет', 'Diabetes gestacional', 'gynecological', 'Diabetes that develops during pregnancy from altered glucose regulation.', 'Диабет, развивающийся во время беременности.', 'Diabetes que se desarrolla durante el embarazo por una regulacion alterada de la glucosa.', '{pancreas,uterus,placenta}', 'Glucose levels affect the pregnancy and fetal health.', 'Уровень глюкозы влияет на течение беременности и здоровье плода.', 'Los niveles de glucosa afectan el embarazo y la salud fetal.', 'Glucose monitoring, nutrition, movement and obstetric care.', 'Контроль глюкозы, питание, движение и наблюдение акушера.', 'Monitoreo de glucosa, nutricion, movimiento y atencion obstetrica.', FALSE, 'moderate'),
  ('preeclampsia', 'Preeclampsia', 'Преэклампсия', 'Preeclampsia', 'gynecological', 'A pregnancy complication with high blood pressure and organ stress.', 'Осложнение беременности, характеризующееся высоким давлением и повреждением органов.', 'Una complicacion del embarazo con presion arterial alta y dano organico.', '{placenta,kidneys,medulla,hypothalamus}', 'High blood pressure strains the kidneys, brain and placenta and needs monitoring.', 'Высокое давление нагружает почки, мозг и плаценту — требует наблюдения.', 'La presion alta sobrecarga los rinones, el cerebro y la placenta y requiere vigilancia.', 'Close monitoring, blood pressure control and timely medical care.', 'Тщательное наблюдение, контроль давления и своевременная медицинская помощь.', 'Vigilancia estrecha, control de la presion y atencion medica oportuna.', FALSE, 'severe'),
  ('hyperemesis-gravidarum', 'Hyperemesis gravidarum', 'Гиперемезис беременных', 'Hiperemesis gravidica', 'gynecological', 'A severe form of pregnancy nausea with persistent vomiting.', 'Тяжёлая форма раннего токсикоза с многократной рвотой.', 'Una forma grave de nausea del embarazo con vomitos persistentes.', '{stomach,medulla,hypothalamus}', 'Persistent vomiting disrupts nutrition, hydration and wellbeing.', 'Многократная рвота нарушает питание, гидратацию и самочувствие.', 'Los vomitos persistentes alteran la nutricion, la hidratacion y el bienestar.', 'Hydration, small frequent meals and medical support.', 'Гидратация, дробное питание и медицинская поддержка.', 'Hidratacion, comidas pequenas y frecuentes y apoyo medico.', FALSE, 'moderate'),
  ('placenta-previa', 'Placenta previa', 'Предлежание плаценты', 'Placenta previa', 'gynecological', 'An abnormal placental position covering or near the cervix.', 'Аномальное расположение плаценты, перекрывающее или прилегающее к шейке матки.', 'Una posicion anormal de la placenta que cubre o esta cerca del cuello uterino.', '{placenta,uterus,cervix}', 'The placental position raises bleeding risk and needs monitoring.', 'Положение плаценты повышает риск кровотечения и требует наблюдения.', 'La posicion de la placenta aumenta el riesgo de sangrado y requiere vigilancia.', 'Obstetric monitoring, activity limits and a delivery plan.', 'Наблюдение акушера, ограничение нагрузок и план родоразрешения.', 'Vigilancia obstetrica, limites de actividad y un plan de parto.', FALSE, 'severe'),
  ('mastitis', 'Mastitis', 'Мастит', 'Mastitis', 'gynecological', 'Inflammation of breast tissue, often during breastfeeding.', 'Воспаление молочной железы.', 'Inflamacion del tejido mamario, a menudo durante la lactancia.', '{breasts}', 'Pain, swelling and fever affect feeding and wellbeing.', 'Боль, отёк и температура влияют на кормление и самочувствие.', 'El dolor, la hinchazon y la fiebre afectan la lactancia y el bienestar.', 'Continued feeding or pumping, rest and medical care if needed.', 'Продолжение кормления/сцеживания, отдых и медицинская помощь при необходимости.', 'Continuar la lactancia o extraccion, descanso y atencion medica si es necesario.', FALSE, 'mild'),
  ('breast-engorgement', 'Breast engorgement', 'Лактостаз', 'Congestion mamaria', 'gynecological', 'A build-up of milk causing breast fullness and discomfort.', 'Застой молока в груди.', 'Una acumulacion de leche que causa plenitud y molestias en las mamas.', '{breasts}', 'Fullness and discomfort make feeding harder.', 'Переполнение и дискомфорт затрудняют кормление.', 'La plenitud y las molestias dificultan la lactancia.', 'Regular feeding or pumping, warm/cold compresses and gentle massage.', 'Регулярное кормление/сцеживание, тепло/холод и мягкий массаж.', 'Lactancia o extraccion regular, compresas frio/calor y masaje suave.', FALSE, 'mild')
ON CONFLICT (slug) DO NOTHING;

-- Idempotent region/category refresh (corrects rows if they pre-exist with stale data).
UPDATE human_conditions SET affected_region_ids = '{uterus,ovaries,fallopian-tubes}', category = 'gynecological' WHERE slug = 'endometriosis';
UPDATE human_conditions SET affected_region_ids = '{ovaries,hypothalamus,pituitary}', category = 'gynecological' WHERE slug = 'pcos';
UPDATE human_conditions SET affected_region_ids = '{uterus}', category = 'gynecological' WHERE slug = 'uterine-fibroids';
UPDATE human_conditions SET affected_region_ids = '{cervix}', category = 'gynecological' WHERE slug = 'cervical-dysplasia';
UPDATE human_conditions SET affected_region_ids = '{vagina}', category = 'gynecological' WHERE slug = 'vaginitis';
UPDATE human_conditions SET affected_region_ids = '{pancreas,uterus,placenta}', category = 'gynecological' WHERE slug = 'gestational-diabetes';
UPDATE human_conditions SET affected_region_ids = '{placenta,kidneys,medulla,hypothalamus}', category = 'gynecological' WHERE slug = 'preeclampsia';
UPDATE human_conditions SET affected_region_ids = '{stomach,medulla,hypothalamus}', category = 'gynecological' WHERE slug = 'hyperemesis-gravidarum';
UPDATE human_conditions SET affected_region_ids = '{placenta,uterus,cervix}', category = 'gynecological' WHERE slug = 'placenta-previa';
UPDATE human_conditions SET affected_region_ids = '{breasts}', category = 'gynecological' WHERE slug = 'mastitis';
UPDATE human_conditions SET affected_region_ids = '{breasts}', category = 'gynecological' WHERE slug = 'breast-engorgement';
