// PR — Sports sub-section of the Functions tab (migration 055).
// Educational reference only — NOT medical / training advice. Grounded in
// general sports-medicine consensus (Mayo Clinic, NIH/NIAMS, AHA physical-
// activity guidance). Positive tissues = what the sport chiefly conditions /
// benefits; negative tissues = characteristic overuse / injury load.
//
// target_tissues_* use the SAME BodyAtlas seed-id vocabulary as medications
// (see MED_SEED / SPORT_SEED in account.html). Mesh-backed seeds
// (brain, heart, lungs, spinal_cord …) tint in 3D; system seeds
// (muscles, bones, joints, vessels, skin) render as coloured chips only.
//
// Field contract mirrors the `sports` table (migration 055):
//   slug, category, name_ru/en/es, description_ru/en/es,
//   target_tissues_positive[], target_tissues_negative[],
//   warning_ru/en/es, sort_order

'use strict';

const SPORTS = [
  /* ── Cardio / endurance ─────────────────────────────────────────────── */
  {
    slug: 'running', category: 'endurance', sort_order: 1,
    name_ru: 'Бег', name_en: 'Running', name_es: 'Correr',
    description_ru: 'Циклическая аэробная нагрузка. Развивает выносливость сердечно-сосудистой и дыхательной систем, укрепляет мышцы ног и — за счёт ударной нагрузки — плотность костей. Повышает выработку BDNF и эндорфинов, улучшает настроение и сон.',
    description_en: 'Cyclic aerobic exercise. Builds cardiovascular and respiratory endurance, strengthens leg muscles and — through impact loading — bone density. Raises BDNF and endorphin output, improving mood and sleep.',
    description_es: 'Ejercicio aeróbico cíclico. Desarrolla la resistencia cardiovascular y respiratoria, fortalece los músculos de las piernas y, por el impacto, la densidad ósea. Aumenta el BDNF y las endorfinas, mejorando el ánimo y el sueño.',
    target_tissues_positive: ['quadriceps', 'hamstrings', 'calves', 'glutes', 'heart', 'lungs', 'motor_cortex', 'cerebellum'],
    target_tissues_negative: ['knee', 'ankle', 'spine_lumbar', 'achilles', 'plantar_fascia'],
    warning_ru: 'Ударная нагрузка на колени, голеностоп и стопы. Наращивайте объём постепенно (правило +10%/нед), нужна амортизирующая обувь и разминка.',
    warning_en: 'Impact loads the knees, ankles and feet. Increase volume gradually (~10%/week rule); cushioned shoes and a warm-up are essential.',
    warning_es: 'El impacto carga rodillas, tobillos y pies. Aumente el volumen de forma gradual (~10%/semana); calzado amortiguado y calentamiento son esenciales.'
  },
  {
    slug: 'walking', category: 'endurance', sort_order: 2,
    name_ru: 'Ходьба', name_en: 'Walking', name_es: 'Caminar',
    description_ru: 'Низкоударная аэробная активность, доступная почти всем. Улучшает работу сердца и сосудов, контроль сахара и веса, настроение; бережна к суставам. Быстрая ходьба даёт умеренную кардионагрузку.',
    description_en: 'Low-impact aerobic activity accessible to almost everyone. Improves heart and vessel health, glucose and weight control and mood while sparing the joints. Brisk walking delivers moderate cardio load.',
    description_es: 'Actividad aeróbica de bajo impacto accesible para casi todos. Mejora el corazón y los vasos, el control de la glucosa y del peso y el ánimo, cuidando las articulaciones.',
    target_tissues_positive: ['quadriceps', 'calves', 'glutes', 'heart', 'vessels', 'hippocampus'],
    target_tissues_negative: [],
    warning_ru: 'Практически без противопоказаний. При боли в стопах — удобная обувь и ортопедические стельки.',
    warning_en: 'Very few contraindications. For foot pain use comfortable shoes and orthotic insoles.',
    warning_es: 'Muy pocas contraindicaciones. Para el dolor de pies use calzado cómodo y plantillas ortopédicas.'
  },
  {
    slug: 'swimming', category: 'endurance', sort_order: 3,
    name_ru: 'Плавание', name_en: 'Swimming', name_es: 'Natación',
    description_ru: 'Аэробная нагрузка всего тела без ударов по суставам. Развивает сердце и лёгкие, мышцы спины, плечевого пояса и кора, увеличивает подвижность суставов. Идеально при лишнем весе и болях в спине.',
    description_en: 'Whole-body aerobic exercise with no joint impact. Develops the heart and lungs, back, shoulder-girdle and core muscles and joint mobility. Ideal for excess weight and back pain.',
    description_es: 'Ejercicio aeróbico de todo el cuerpo sin impacto articular. Desarrolla corazón y pulmones, músculos de espalda, hombros y core, y la movilidad articular.',
    target_tissues_positive: ['deltoids', 'latissimus', 'rotator_cuff', 'core', 'quadriceps', 'heart', 'lungs'],
    target_tissues_negative: ['shoulder', 'spine_cervical'],
    warning_ru: 'Плечо пловца при перегрузке кроля. Хлорированная вода сушит кожу и волосы; не плавать в одиночку.',
    warning_en: 'Swimmer’s shoulder from freestyle overuse. Chlorinated water dries skin and hair; never swim alone.',
    warning_es: 'Hombro del nadador por sobreuso del crol. El agua clorada reseca la piel y el cabello; nunca nade solo.'
  },
  {
    slug: 'cycling', category: 'endurance', sort_order: 4,
    name_ru: 'Велоспорт', name_en: 'Cycling', name_es: 'Ciclismo',
    description_ru: 'Аэробная нагрузка с низким ударным воздействием на суставы. Мощно развивает сердце, лёгкие и мышцы ног, помогает контролировать вес. Подходит для реабилитации коленей.',
    description_en: 'Aerobic exercise with low joint impact. Powerfully develops the heart, lungs and leg muscles and aids weight control. Suitable for knee rehabilitation.',
    description_es: 'Ejercicio aeróbico de bajo impacto articular. Desarrolla con fuerza el corazón, los pulmones y los músculos de las piernas y ayuda al control del peso.',
    target_tissues_positive: ['quadriceps', 'hamstrings', 'calves', 'glutes', 'heart', 'lungs', 'vessels'],
    target_tissues_negative: ['knee', 'spine_lumbar', 'wrist'],
    warning_ru: 'Наклонная посадка нагружает поясницу и шею; онемение кистей и промежности при неверной подгонке. Обязателен шлем.',
    warning_en: 'The forward posture loads the lower back and neck; hand and perineal numbness with poor bike fit. A helmet is mandatory.',
    warning_es: 'La postura inclinada carga la zona lumbar y el cuello; entumecimiento de manos y periné con mal ajuste. El casco es obligatorio.'
  },
  {
    slug: 'rowing', category: 'endurance', sort_order: 5,
    name_ru: 'Гребля', name_en: 'Rowing', name_es: 'Remo',
    description_ru: 'Аэробно-силовая нагрузка, задействующая ~85% мышц. Развивает сердце, лёгкие, мышцы спины, ног и кора одновременно, с низким ударным воздействием.',
    description_en: 'Combined aerobic-strength effort using ~85% of the body’s muscles. Simultaneously develops the heart, lungs, back, legs and core with low impact.',
    description_es: 'Esfuerzo aeróbico y de fuerza que emplea ~85% de los músculos. Desarrolla a la vez corazón, pulmones, espalda, piernas y core con bajo impacto.',
    target_tissues_positive: ['latissimus', 'trapezius', 'erector_spinae', 'quadriceps', 'glutes', 'core', 'heart', 'lungs'],
    target_tissues_negative: ['spine_lumbar', 'knee', 'wrist'],
    warning_ru: 'Круглая спина под нагрузкой травмирует поясницу. Техника «ноги → корпус → руки» и жёсткий поясничный контроль обязательны.',
    warning_en: 'A rounded back under load injures the lumbar spine. The “legs → body → arms” sequence and firm lumbar control are essential.',
    warning_es: 'Una espalda redondeada bajo carga lesiona la zona lumbar. La secuencia “piernas → tronco → brazos” y el control lumbar son esenciales.'
  },

  /* ── Team / ball sports ─────────────────────────────────────────────── */
  {
    slug: 'tennis', category: 'team_ball', sort_order: 10,
    name_ru: 'Теннис', name_en: 'Tennis', name_es: 'Tenis',
    description_ru: 'Интервальная нагрузка со спринтами, сменой направлений и ударами. Развивает сердце, мышцы, координацию и — за счёт нагрузки — плотность костей; тренирует реакцию и концентрацию.',
    description_en: 'Interval exercise with sprints, direction changes and strokes. Builds the heart, muscles, coordination and — through loading — bone density; trains reaction and focus.',
    description_es: 'Ejercicio interválico con esprints, cambios de dirección y golpes. Desarrolla el corazón, los músculos, la coordinación y la densidad ósea; entrena la reacción.',
    target_tissues_positive: ['deltoids', 'forearms', 'quadriceps', 'calves', 'core', 'cardiovascular', 'motor_cortex'],
    target_tissues_negative: ['elbow', 'shoulder', 'wrist', 'spine_lumbar', 'ankle'],
    warning_ru: '«Локоть теннисиста», травмы плеча, колена и голеностопа при рывках. Нужна разминка и грамотная техника удара.',
    warning_en: 'Tennis elbow, shoulder, knee and ankle injuries from cutting movements. Warm-up and sound stroke technique are needed.',
    warning_es: 'Codo de tenista y lesiones de hombro, rodilla y tobillo por los cambios bruscos. Calentamiento y buena técnica son necesarios.'
  },
  {
    slug: 'basketball', category: 'team_ball', sort_order: 11,
    name_ru: 'Баскетбол', name_en: 'Basketball', name_es: 'Baloncesto',
    description_ru: 'Высокоинтенсивная командная игра с прыжками, спринтами и остановками. Развивает сердце, лёгкие, мышцы ног, координацию и плотность костей.',
    description_en: 'High-intensity team game with jumps, sprints and stops. Develops the heart, lungs, leg muscles, coordination and bone density.',
    description_es: 'Juego de equipo de alta intensidad con saltos, esprints y frenadas. Desarrolla corazón, pulmones, músculos de las piernas, coordinación y densidad ósea.',
    target_tissues_positive: ['quadriceps', 'calves', 'glutes', 'core', 'deltoids', 'cardiovascular', 'cerebellum'],
    target_tissues_negative: ['knee', 'ankle', 'spine_lumbar'],
    warning_ru: 'Высокий риск травм голеностопа и разрыва ПКС при приземлениях и разворотах. Нужны фиксирующая обувь и укрепление коленей.',
    warning_en: 'High risk of ankle sprains and ACL tears on landings and pivots. Supportive shoes and knee strengthening help.',
    warning_es: 'Alto riesgo de esguinces de tobillo y roturas del LCA en aterrizajes y giros. Ayudan calzado de sujeción y fortalecer las rodillas.'
  },
  {
    slug: 'football', category: 'team_ball', sort_order: 12,
    name_ru: 'Футбол', name_en: 'Football (soccer)', name_es: 'Fútbol',
    description_ru: 'Командная игра на выносливость с постоянными спринтами. Отлично развивает сердце, лёгкие, мышцы ног и плотность костей, тренирует координацию и командное мышление.',
    description_en: 'Endurance team game with constant sprints. Excellently develops the heart, lungs, leg muscles and bone density; trains coordination and team thinking.',
    description_es: 'Juego de equipo de resistencia con esprints constantes. Desarrolla el corazón, los pulmones, los músculos de las piernas y la densidad ósea.',
    target_tissues_positive: ['quadriceps', 'hamstrings', 'calves', 'glutes', 'core', 'cardiovascular', 'motor_cortex'],
    target_tissues_negative: ['knee', 'ankle', 'brain', 'spine_lumbar'],
    warning_ru: 'Разрывы ПКС и мениска, травмы голеностопа; сотрясения и микротравмы мозга при ударах головой. Ограничивайте игру головой у подростков.',
    warning_en: 'ACL and meniscus tears, ankle injuries; concussion and sub-concussive brain load from heading. Limit heading in youth.',
    warning_es: 'Roturas de LCA y menisco, lesiones de tobillo; conmociones y carga cerebral por cabecear. Limite el cabeceo en jóvenes.'
  },

  /* ── Combat / strength ──────────────────────────────────────────────── */
  {
    slug: 'boxing', category: 'combat', sort_order: 20,
    name_ru: 'Бокс', name_en: 'Boxing', name_es: 'Boxeo',
    description_ru: 'Интервальная нагрузка высокой интенсивности. Развивает сердце, лёгкие, мышцы плечевого пояса и кора, скорость реакции и координацию. Мощно снимает стресс.',
    description_en: 'High-intensity interval training. Builds the heart, lungs, shoulder-girdle and core muscles, reaction speed and coordination. A powerful stress outlet.',
    description_es: 'Entrenamiento interválico de alta intensidad. Desarrolla corazón, pulmones, músculos de hombros y core, velocidad de reacción y coordinación.',
    target_tissues_positive: ['deltoids', 'triceps', 'biceps', 'forearms', 'core', 'obliques', 'cardiovascular', 'motor_cortex'],
    target_tissues_negative: ['brain', 'prefrontal_cortex', 'wrist', 'hand', 'nose', 'orbital'],
    warning_ru: 'Спарринг несёт риск сотрясений и хронической травматической энцефалопатии (ХТЭ), переломов кисти и носа, рассечений. Защитный шлем и капа обязательны; удары в голову — по показаниям.',
    warning_en: 'Sparring carries a risk of concussion and chronic traumatic encephalopathy (CTE), hand and nose fractures and cuts. Headgear and a mouthguard are essential; limit head contact.',
    warning_es: 'El sparring conlleva riesgo de conmoción y encefalopatía traumática crónica (ETC), fracturas de mano y nariz y cortes. Casco y protector bucal son esenciales.'
  },
  {
    slug: 'wrestling', category: 'combat', sort_order: 21,
    name_ru: 'Борьба', name_en: 'Wrestling', name_es: 'Lucha',
    description_ru: 'Силовое единоборство всего тела. Развивает мышцы, силовую выносливость, плотность костей и сердечно-сосудистую систему, тренирует баланс и волю.',
    description_en: 'Whole-body strength combat sport. Builds muscle, strength-endurance, bone density and the cardiovascular system; trains balance and grit.',
    description_es: 'Deporte de combate de fuerza de todo el cuerpo. Desarrolla músculo, resistencia a la fuerza, densidad ósea y el sistema cardiovascular.',
    target_tissues_positive: ['trapezius', 'latissimus', 'deltoids', 'core', 'quadriceps', 'glutes', 'forearms', 'cardiovascular'],
    target_tissues_negative: ['shoulder', 'spine_cervical', 'knee', 'elbow', 'skin'],
    warning_ru: 'Вывихи и травмы плеча, колена, шеи; кожные инфекции (герпес, стригущий лишай), «ухо борца». Резкий сгон веса опасен.',
    warning_en: 'Shoulder, knee and neck injuries and dislocations; skin infections (herpes, ringworm), cauliflower ear. Rapid weight cutting is dangerous.',
    warning_es: 'Luxaciones y lesiones de hombro, rodilla y cuello; infecciones cutáneas, oreja de coliflor. El corte rápido de peso es peligroso.'
  },
  {
    slug: 'martial-arts', category: 'combat', sort_order: 22,
    name_ru: 'Боевые искусства', name_en: 'Martial arts', name_es: 'Artes marciales',
    description_ru: 'Каратэ, дзюдо, тхэквондо, ММА и др. Развивают сердце, мышцы, гибкость, координацию, плотность костей, дисциплину и концентрацию.',
    description_en: 'Karate, judo, taekwondo, MMA and others. Develop the heart, muscles, flexibility, coordination, bone density, discipline and focus.',
    description_es: 'Kárate, judo, taekwondo, MMA y otros. Desarrollan corazón, músculos, flexibilidad, coordinación, densidad ósea, disciplina y concentración.',
    target_tissues_positive: ['quadriceps', 'hamstrings', 'calves', 'core', 'deltoids', 'cardiovascular', 'cerebellum', 'motor_cortex'],
    target_tissues_negative: ['brain', 'knee', 'ankle', 'wrist', 'hand'],
    warning_ru: 'Контактные стили несут риск сотрясений, вывихов и переломов. Спарринг в защите, под контролем тренера, с постепенным ростом контакта.',
    warning_en: 'Contact styles risk concussion, dislocations and fractures. Spar with protective gear under a coach, escalating contact gradually.',
    warning_es: 'Los estilos de contacto arriesgan conmociones, luxaciones y fracturas. Haga sparring con protección y bajo supervisión.'
  },
  {
    slug: 'weightlifting', category: 'strength', sort_order: 23,
    name_ru: 'Тяжёлая атлетика', name_en: 'Weightlifting', name_es: 'Levantamiento de pesas',
    description_ru: 'Силовая тренировка с отягощениями. Наращивает мышечную массу и силу, повышает плотность костей и чувствительность к инсулину, укрепляет связки и сухожилия.',
    description_en: 'Resistance strength training. Builds muscle mass and strength, raises bone density and insulin sensitivity, strengthens ligaments and tendons.',
    description_es: 'Entrenamiento de fuerza con cargas. Aumenta la masa y la fuerza muscular, la densidad ósea y la sensibilidad a la insulina.',
    target_tissues_positive: ['quadriceps', 'glutes', 'erector_spinae', 'trapezius', 'deltoids', 'pectorals', 'latissimus', 'core'],
    target_tissues_negative: ['spine_lumbar', 'shoulder', 'knee', 'wrist'],
    warning_ru: 'Травмы поясницы, плеч и коленей при плохой технике или чрезмерном весе. Освойте технику с малым весом; натуживание опасно при гипертонии.',
    warning_en: 'Lower-back, shoulder and knee injuries from poor form or excess load. Master technique light first; the Valsalva strain is risky in hypertension.',
    warning_es: 'Lesiones lumbares, de hombro y rodilla por mala técnica o exceso de carga. Domine la técnica con poco peso primero.'
  },

  /* ── Mind-body / mobility ───────────────────────────────────────────── */
  {
    slug: 'yoga', category: 'mind_body', sort_order: 30,
    name_ru: 'Йога', name_en: 'Yoga', name_es: 'Yoga',
    description_ru: 'Сочетание поз, растяжки и дыхания. Развивает гибкость, силу и баланс мышц, подвижность позвоночника; дыхательные практики снижают стресс и активируют парасимпатику.',
    description_en: 'Combines postures, stretching and breathing. Develops flexibility, muscular strength and balance and spinal mobility; breath work lowers stress and engages the parasympathetic system.',
    description_es: 'Combina posturas, estiramientos y respiración. Desarrolla flexibilidad, fuerza y equilibrio muscular y movilidad de la columna; reduce el estrés.',
    target_tissues_positive: ['core', 'hamstrings', 'hip_flexors', 'erector_spinae', 'deltoids', 'prefrontal_cortex', 'lungs'],
    target_tissues_negative: ['wrist', 'spine_lumbar'],
    warning_ru: 'Форсированные прогибы и стойки на голове/плечах опасны для шеи и поясницы. Входите в асаны без боли, избегайте гиперрастяжения суставов.',
    warning_en: 'Forced backbends and head/shoulder stands risk the neck and lower back. Enter poses without pain; avoid over-stretching joints.',
    warning_es: 'Las flexiones forzadas y las posturas invertidas arriesgan cuello y zona lumbar. Entre en las posturas sin dolor.'
  },
  {
    slug: 'pilates', category: 'mind_body', sort_order: 31,
    name_ru: 'Пилатес', name_en: 'Pilates', name_es: 'Pilates',
    description_ru: 'Контролируемые упражнения на кор, осанку и стабилизацию. Укрепляет глубокие мышцы живота и спины, улучшает осанку и подвижность позвоночника, снижает боли в пояснице.',
    description_en: 'Controlled core, posture and stabilisation exercise. Strengthens the deep abdominal and back muscles, improves posture and spinal mobility and eases lower-back pain.',
    description_es: 'Ejercicio controlado de core, postura y estabilización. Fortalece los músculos profundos del abdomen y la espalda y mejora la postura.',
    target_tissues_positive: ['core', 'obliques', 'erector_spinae', 'glutes', 'hip_flexors', 'prefrontal_cortex'],
    target_tissues_negative: ['spine_cervical'],
    warning_ru: 'Как правило безопасен. При грыжах диска и остеопорозе избегайте глубокого сгибания позвоночника — консультация со специалистом.',
    warning_en: 'Generally safe. With disc herniation or osteoporosis avoid deep spinal flexion — consult a specialist.',
    warning_es: 'Generalmente seguro. Con hernias de disco u osteoporosis evite la flexión profunda de la columna — consulte a un especialista.'
  },
  {
    slug: 'dance', category: 'mind_body', sort_order: 32,
    name_ru: 'Танцы', name_en: 'Dance', name_es: 'Baile',
    description_ru: 'Ритмичная аэробная нагрузка. Развивает сердце, мышцы, координацию, баланс и плотность костей; заучивание связок тренирует мозг и память, поднимает настроение.',
    description_en: 'Rhythmic aerobic activity. Develops the heart, muscles, coordination, balance and bone density; learning routines trains the brain and memory and lifts mood.',
    description_es: 'Actividad aeróbica rítmica. Desarrolla el corazón, los músculos, la coordinación, el equilibrio y la densidad ósea; entrena el cerebro y el ánimo.',
    target_tissues_positive: ['quadriceps', 'calves', 'glutes', 'core', 'hip_flexors', 'cardiovascular', 'cerebellum', 'motor_cortex'],
    target_tissues_negative: ['ankle', 'knee', 'foot', 'hip'],
    warning_ru: 'Травмы голеностопа, колена и стопы, особенно в танцах на пуантах. Нужна подходящая обувь, покрытие и разминка.',
    warning_en: 'Ankle, knee and foot injuries, especially in pointe dance. Proper footwear, flooring and a warm-up are needed.',
    warning_es: 'Lesiones de tobillo, rodilla y pie, sobre todo en danza de puntas. Se necesitan calzado, suelo adecuado y calentamiento.'
  },

  /* ── Cognitive ──────────────────────────────────────────────────────── */
  {
    slug: 'chess', category: 'cognitive', sort_order: 40,
    name_ru: 'Шахматы', name_en: 'Chess', name_es: 'Ajedrez',
    description_ru: 'Интеллектуальный вид спорта. Тренирует память, внимание, расчёт вариантов, стратегическое мышление и эмоциональную саморегуляцию под давлением времени. Замедляет когнитивное старение.',
    description_en: 'A cognitive sport. Trains memory, attention, calculation, strategic thinking and emotional self-regulation under time pressure. Slows cognitive ageing.',
    description_es: 'Un deporte cognitivo. Entrena la memoria, la atención, el cálculo, el pensamiento estratégico y la autorregulación emocional bajo presión de tiempo.',
    target_tissues_positive: ['prefrontal_cortex', 'hippocampus', 'parietal_cortex'],
    target_tissues_negative: ['spine_cervical', 'spine_lumbar', 'vessels'],
    warning_ru: 'Сидячий вид спорта: многочасовые партии вредят осанке и кровообращению. Делайте перерывы, разминайте спину, поддерживайте общую физическую активность.',
    warning_en: 'A sedentary sport: multi-hour games harm posture and circulation. Take breaks, mobilise the back and keep up general physical activity.',
    warning_es: 'Un deporte sedentario: las partidas de varias horas dañan la postura y la circulación. Tome descansos y mantenga actividad física general.'
  }
];

// Map a sport slug → catalog diagnosis / human_condition slugs it commonly
// benefits (therapeutic recommendation). Keyed by diagnosis slug like
// DIAG_LINKS in medications-seed. TEXT slug join, no FK, unknown slugs harmless.
const SPORT_DIAG_LINKS = {
  // populated conservatively; sports↔condition benefit links are advisory only.
  // Slugs MUST match the live human_conditions catalog (migrations 018/023):
  // anxiety→gad, type-2-diabetes→type2-diabetes, osteoporosis has no row → use
  // the musculoskeletal conditions that load-bearing sport actually helps.
  'depression':      [ { slug: 'running', is_primary: true }, { slug: 'walking' }, { slug: 'swimming' }, { slug: 'yoga' } ],
  'gad':             [ { slug: 'yoga', is_primary: true }, { slug: 'swimming' }, { slug: 'walking' }, { slug: 'boxing' } ],
  'type2-diabetes':  [ { slug: 'walking', is_primary: true }, { slug: 'running' }, { slug: 'cycling' }, { slug: 'weightlifting' } ],
  'hypertension':    [ { slug: 'walking', is_primary: true }, { slug: 'swimming' }, { slug: 'cycling' } ],
  'hip-osteoarthritis':     [ { slug: 'swimming', is_primary: true }, { slug: 'cycling' }, { slug: 'pilates' } ],
  'spinal-osteochondrosis': [ { slug: 'pilates', is_primary: true }, { slug: 'swimming' }, { slug: 'yoga' } ]
};

// ── Sports-injury catalog (PR: common_injuries) ─────────────────────────────
// New rows for the human_conditions table. Educational reference only; grounded
// in general sports-medicine consensus (Mayo Clinic, NIH/NIAMS, ACSM). category
// 'sports-injury'; affected_region_ids use BodyAtlas seed-ids (empty for limb /
// soft-tissue injuries with no dedicated mesh — the card still renders list-only).
// Existing catalog rows (disc-herniation, hip-osteoarthritis, spinal-osteochondrosis)
// are reused by slug in SPORT_INJURIES and are NOT redefined here.
const INJURY_CONDITIONS = [
  { slug: 'concussion', category: 'sports-injury', severity: 'moderate', regions: ['frontal-lobe','cortex','brainstem'],
    name_ru: 'Сотрясение мозга', name_en: 'Concussion', name_es: 'Conmoción cerebral',
    desc_ru: 'Лёгкая черепно-мозговая травма от удара или резкого ускорения головы, временно нарушающая работу мозга.',
    desc_en: 'A mild traumatic brain injury from a blow or rapid head acceleration that temporarily disrupts brain function.',
    desc_es: 'Lesión cerebral traumática leve por un golpe o aceleración brusca de la cabeza que altera temporalmente la función cerebral.',
    imp_ru: 'Головная боль, головокружение, спутанность, тошнота, свето- и звукочувствительность; иногда потеря сознания.',
    imp_en: 'Headache, dizziness, confusion, nausea, light and noise sensitivity; sometimes brief loss of consciousness.',
    imp_es: 'Dolor de cabeza, mareo, confusión, náuseas, sensibilidad a luz y ruido; a veces pérdida breve de conciencia.',
    rec_ru: 'Немедленно прекратить игру, обследование, покой мозга; возврат к спорту — только ступенчато под контролем врача.',
    rec_en: 'Stop play immediately, seek evaluation, rest the brain; return to sport only stepwise under medical guidance.',
    rec_es: 'Detenga el juego de inmediato, evalúe, descanse el cerebro; regrese al deporte de forma gradual y supervisada.' },
  { slug: 'cte', category: 'sports-injury', severity: 'severe', regions: ['frontal-lobe','temporal-lobe','cortex'],
    name_ru: 'Хроническая травматическая энцефалопатия (ХТЭ)', name_en: 'Chronic traumatic encephalopathy (CTE)', name_es: 'Encefalopatía traumática crónica (ETC)',
    desc_ru: 'Прогрессирующая дегенерация мозга от повторных сотрясений и субконкуссивных ударов (бокс, американский футбол).',
    desc_en: 'Progressive brain degeneration from repeated concussive and sub-concussive impacts (boxing, American football).',
    desc_es: 'Degeneración cerebral progresiva por impactos repetidos, conmocionales y subconmocionales (boxeo, fútbol americano).',
    imp_ru: 'Со временем — расстройства памяти, настроения, поведения, паркинсонизм; диагноз подтверждается посмертно.',
    imp_en: 'Over time — memory, mood and behaviour changes, parkinsonism; confirmed diagnosis is post-mortem.',
    imp_es: 'Con el tiempo — cambios de memoria, ánimo y conducta, parkinsonismo; el diagnóstico se confirma post mortem.',
    rec_ru: 'Профилактика решает: ограничение ударов по голове, защита, обязательный протокол при сотрясении.',
    rec_en: 'Prevention is key: limit head impacts, use protection, follow strict concussion protocols.',
    rec_es: 'La prevención es clave: limitar los golpes en la cabeza, usar protección y seguir protocolos de conmoción.' },
  { slug: 'runners-knee', category: 'sports-injury', severity: 'mild', regions: [],
    name_ru: 'Колено бегуна (пателлофеморальный синдром)', name_en: "Runner's knee (patellofemoral pain)", name_es: 'Rodilla del corredor (dolor patelofemoral)',
    desc_ru: 'Боль вокруг надколенника от перегрузки и неправильного скольжения коленной чашечки.',
    desc_en: 'Pain around the kneecap from overload and poor patellar tracking.',
    desc_es: 'Dolor alrededor de la rótula por sobrecarga y mal deslizamiento rotuliano.',
    imp_ru: 'Тупая боль спереди колена при беге, приседаниях и спуске по лестнице.',
    imp_en: 'Dull pain at the front of the knee when running, squatting or descending stairs.',
    imp_es: 'Dolor sordo en la parte frontal de la rodilla al correr, ponerse en cuclillas o bajar escaleras.',
    rec_ru: 'Снизить объём, укреплять квадрицепс и ягодичные, коррекция техники и обуви.',
    rec_en: 'Reduce volume, strengthen quadriceps and glutes, correct technique and footwear.',
    rec_es: 'Reduzca el volumen, fortalezca cuádriceps y glúteos, corrija técnica y calzado.' },
  { slug: 'itb-syndrome', category: 'sports-injury', severity: 'mild', regions: [],
    name_ru: 'Синдром илиотибиального тракта', name_en: 'Iliotibial band syndrome', name_es: 'Síndrome de la banda iliotibial',
    desc_ru: 'Воспаление и трение подвздошно-большеберцового тракта о наружный мыщелок бедра.',
    desc_en: 'Inflammation and friction of the iliotibial band over the outer knee.',
    desc_es: 'Inflamación y fricción de la banda iliotibial sobre el cóndilo externo de la rodilla.',
    imp_ru: 'Жгучая боль по наружной стороне колена, усиливается на длинных дистанциях и спусках.',
    imp_en: 'Burning pain on the outer knee, worse over long distances and downhills.',
    imp_es: 'Dolor ardiente en la cara externa de la rodilla, peor en distancias largas y bajadas.',
    rec_ru: 'Отдых, растяжка и укрепление ягодичных/абдукторов, постепенное наращивание нагрузки.',
    rec_en: 'Rest, stretch and strengthen glutes/abductors, build load gradually.',
    rec_es: 'Descanso, estiramiento y fortalecimiento de glúteos/abductores, carga gradual.' },
  { slug: 'plantar-fasciitis', category: 'sports-injury', severity: 'mild', regions: [],
    name_ru: 'Плантарный фасциит', name_en: 'Plantar fasciitis', name_es: 'Fascitis plantar',
    desc_ru: 'Воспаление подошвенной фасции от ударной нагрузки — частая причина боли в пятке.',
    desc_en: 'Inflammation of the plantar fascia from impact loading — a common cause of heel pain.',
    desc_es: 'Inflamación de la fascia plantar por el impacto — causa frecuente de dolor de talón.',
    imp_ru: 'Острая боль в пятке при первых шагах утром и после нагрузки.',
    imp_en: 'Sharp heel pain with the first steps in the morning and after activity.',
    imp_es: 'Dolor agudo en el talón con los primeros pasos por la mañana y tras la actividad.',
    rec_ru: 'Растяжка стопы и икры, поддерживающая обувь/стельки, снижение ударной нагрузки.',
    rec_en: 'Stretch the foot and calf, supportive shoes/insoles, reduce impact load.',
    rec_es: 'Estire pie y pantorrilla, use calzado/plantillas de soporte, reduzca el impacto.' },
  { slug: 'achilles-tendinopathy', category: 'sports-injury', severity: 'moderate', regions: [],
    name_ru: 'Тендинопатия ахиллова сухожилия', name_en: 'Achilles tendinopathy', name_es: 'Tendinopatía del tendón de Aquiles',
    desc_ru: 'Дегенерация и воспаление ахиллова сухожилия от повторной ударной и прыжковой нагрузки.',
    desc_en: 'Degeneration and inflammation of the Achilles tendon from repeated impact and jumping load.',
    desc_es: 'Degeneración e inflamación del tendón de Aquiles por impacto y saltos repetidos.',
    imp_ru: 'Боль и скованность над пяткой, риск разрыва при резкой нагрузке без лечения.',
    imp_en: 'Pain and stiffness above the heel; risk of rupture with sudden load if untreated.',
    imp_es: 'Dolor y rigidez sobre el talón; riesgo de rotura con carga brusca si no se trata.',
    rec_ru: 'Эксцентрические упражнения на икры, постепенная нагрузка, разминка; при остром разрыве — к врачу.',
    rec_en: 'Eccentric calf loading, gradual progression, warm-up; see a doctor for an acute rupture.',
    rec_es: 'Ejercicios excéntricos de pantorrilla, progresión gradual, calentamiento; consulte ante una rotura aguda.' },
  { slug: 'shin-splints', category: 'sports-injury', severity: 'mild', regions: [],
    name_ru: 'Расколотая голень (тибиальный синдром)', name_en: 'Shin splints (medial tibial stress syndrome)', name_es: 'Periostitis tibial',
    desc_ru: 'Боль по внутреннему краю большеберцовой кости от перегрузки и резкого роста объёма.',
    desc_en: 'Pain along the inner shin from overload and a rapid increase in training volume.',
    desc_es: 'Dolor en el borde interno de la tibia por sobrecarga y aumento rápido del volumen.',
    imp_ru: 'Ноющая боль вдоль голени при беге; без отдыха может перейти в стресс-перелом.',
    imp_en: 'Aching pain along the shin when running; without rest can progress to a stress fracture.',
    imp_es: 'Dolor a lo largo de la espinilla al correr; sin descanso puede evolucionar a fractura por estrés.',
    rec_ru: 'Снизить объём, амортизирующая обувь, укрепление голени, наращивать нагрузку ≤10%/нед.',
    rec_en: 'Reduce volume, cushioned shoes, strengthen the lower leg, progress ≤10%/week.',
    rec_es: 'Reduzca el volumen, calzado amortiguado, fortalezca la pierna, progrese ≤10%/semana.' },
  { slug: 'ankle-sprain', category: 'sports-injury', severity: 'moderate', regions: [],
    name_ru: 'Растяжение связок голеностопа', name_en: 'Ankle sprain', name_es: 'Esguince de tobillo',
    desc_ru: 'Повреждение связок голеностопа при подворачивании стопы — самая частая спортивная травма.',
    desc_en: 'Injury to the ankle ligaments from rolling the foot — the most common sports injury.',
    desc_es: 'Lesión de los ligamentos del tobillo al torcer el pie — la lesión deportiva más común.',
    imp_ru: 'Боль, отёк и нестабильность; повторные растяжения ведут к хронической нестабильности.',
    imp_en: 'Pain, swelling and instability; repeated sprains lead to chronic instability.',
    imp_es: 'Dolor, hinchazón e inestabilidad; los esguinces repetidos causan inestabilidad crónica.',
    rec_ru: 'Покой-лёд-компрессия-возвышение, затем баланс и укрепление; тейп/фиксатор при возврате.',
    rec_en: 'Rest-ice-compression-elevation, then balance and strengthening; tape/brace on return.',
    rec_es: 'Reposo-hielo-compresión-elevación, luego equilibrio y fortalecimiento; vendaje/férula al volver.' },
  { slug: 'acl-tear', category: 'sports-injury', severity: 'severe', regions: [],
    name_ru: 'Разрыв передней крестообразной связки (ПКС)', name_en: 'ACL tear', name_es: 'Rotura del ligamento cruzado anterior (LCA)',
    desc_ru: 'Разрыв передней крестообразной связки колена при развороте, приземлении или резкой остановке.',
    desc_en: 'Rupture of the knee’s anterior cruciate ligament on a pivot, landing or sudden stop.',
    desc_es: 'Rotura del ligamento cruzado anterior de la rodilla al girar, aterrizar o frenar bruscamente.',
    imp_ru: 'Хлопок, боль, отёк и нестабильность колена; часто требует реконструкции и долгой реабилитации.',
    imp_en: 'A pop, pain, swelling and knee instability; often needs reconstruction and long rehab.',
    imp_es: 'Un chasquido, dolor, hinchazón e inestabilidad; suele requerir reconstrucción y rehabilitación larga.',
    rec_ru: 'Обследование, часто операция; профилактика — нейромышечный тренинг и техника приземления.',
    rec_en: 'Evaluation, often surgery; prevention via neuromuscular training and landing technique.',
    rec_es: 'Evaluación, con frecuencia cirugía; prevención con entrenamiento neuromuscular y técnica de aterrizaje.' },
  { slug: 'meniscus-tear', category: 'sports-injury', severity: 'moderate', regions: [],
    name_ru: 'Разрыв мениска', name_en: 'Meniscus tear', name_es: 'Rotura de menisco',
    desc_ru: 'Повреждение хрящевого мениска колена при скручивании под нагрузкой.',
    desc_en: 'Tear of the knee’s cartilage meniscus from twisting under load.',
    desc_es: 'Desgarro del menisco de la rodilla por torsión bajo carga.',
    imp_ru: 'Боль, отёк, щелчки и блокировки колена, ограничение сгибания.',
    imp_en: 'Pain, swelling, clicking and locking of the knee, limited bending.',
    imp_es: 'Dolor, hinchazón, chasquidos y bloqueo de la rodilla, flexión limitada.',
    rec_ru: 'Реабилитация или артроскопия по типу разрыва; укрепление мышц бедра.',
    rec_en: 'Rehab or arthroscopy depending on the tear; strengthen the thigh muscles.',
    rec_es: 'Rehabilitación o artroscopia según el desgarro; fortalezca los músculos del muslo.' },
  { slug: 'rotator-cuff-tear', category: 'sports-injury', severity: 'moderate', regions: [],
    name_ru: 'Разрыв вращательной манжеты плеча', name_en: 'Rotator cuff tear', name_es: 'Rotura del manguito rotador',
    desc_ru: 'Повреждение сухожилий вращательной манжеты от повторных нагрузок над головой.',
    desc_en: 'Injury to the rotator cuff tendons from repetitive overhead loading.',
    desc_es: 'Lesión de los tendones del manguito rotador por carga repetida por encima de la cabeza.',
    imp_ru: 'Боль в плече, слабость при подъёме руки, ночная боль.',
    imp_en: 'Shoulder pain, weakness lifting the arm, night pain.',
    imp_es: 'Dolor de hombro, debilidad al levantar el brazo, dolor nocturno.',
    rec_ru: 'Покой, ЛФК на манжету и лопатку; при полном разрыве — консультация хирурга.',
    rec_en: 'Rest, cuff and scapular rehab; a full-thickness tear needs a surgical opinion.',
    rec_es: 'Descanso, rehabilitación del manguito y la escápula; una rotura completa requiere valoración quirúrgica.' },
  { slug: 'swimmers-shoulder', category: 'sports-injury', severity: 'mild', regions: [],
    name_ru: 'Плечо пловца (импинджмент)', name_en: "Swimmer's shoulder (impingement)", name_es: 'Hombro del nadador (pinzamiento)',
    desc_ru: 'Импинджмент и воспаление сухожилий плеча от тысяч повторов гребка.',
    desc_en: 'Impingement and tendon inflammation of the shoulder from thousands of stroke repetitions.',
    desc_es: 'Pinzamiento e inflamación tendinosa del hombro por miles de repeticiones de brazada.',
    imp_ru: 'Боль в передней части плеча при гребке и подъёме руки.',
    imp_en: 'Pain at the front of the shoulder during the stroke and arm elevation.',
    imp_es: 'Dolor en la parte anterior del hombro durante la brazada y al elevar el brazo.',
    rec_ru: 'Коррекция техники, укрепление манжеты и лопаточных мышц, снижение объёма кроля.',
    rec_en: 'Correct technique, strengthen cuff and scapular muscles, reduce freestyle volume.',
    rec_es: 'Corrija la técnica, fortalezca el manguito y la escápula, reduzca el volumen de crol.' },
  { slug: 'tennis-elbow', category: 'sports-injury', severity: 'mild', regions: [],
    name_ru: 'Локоть теннисиста (латеральный эпикондилит)', name_en: 'Tennis elbow (lateral epicondylitis)', name_es: 'Codo de tenista (epicondilitis lateral)',
    desc_ru: 'Тендинопатия разгибателей предплечья в месте прикрепления к наружному мыщелку локтя.',
    desc_en: 'Tendinopathy of the forearm extensors at their attachment on the outer elbow.',
    desc_es: 'Tendinopatía de los extensores del antebrazo en su inserción en el epicóndilo lateral.',
    imp_ru: 'Боль по наружной стороне локтя при хвате и разгибании запястья.',
    imp_en: 'Pain on the outer elbow with gripping and wrist extension.',
    imp_es: 'Dolor en la cara externa del codo al agarrar y extender la muñeca.',
    rec_ru: 'Разгрузка, эксцентрика на предплечье, коррекция техники и хвата ракетки.',
    rec_en: 'Offload, eccentric forearm work, correct technique and racket grip.',
    rec_es: 'Descargue, trabajo excéntrico del antebrazo, corrija técnica y empuñadura.' },
  { slug: 'lumbar-strain', category: 'sports-injury', severity: 'moderate', regions: ['lumbar-spine'],
    name_ru: 'Растяжение мышц поясницы', name_en: 'Lumbar (lower-back) strain', name_es: 'Distensión lumbar',
    desc_ru: 'Повреждение мышц и связок поясницы при подъёме веса или скручивании с круглой спиной.',
    desc_en: 'Injury to the lower-back muscles and ligaments from lifting or twisting with a rounded back.',
    desc_es: 'Lesión de los músculos y ligamentos lumbares por levantar o girar con la espalda redondeada.',
    imp_ru: 'Острая боль и скованность поясницы, спазм, ограничение наклонов.',
    imp_en: 'Acute lower-back pain and stiffness, spasm, limited bending.',
    imp_es: 'Dolor lumbar agudo y rigidez, espasmo, flexión limitada.',
    rec_ru: 'Относительный покой, движение без боли, техника подъёма, укрепление кора.',
    rec_en: 'Relative rest, pain-free movement, lifting technique, core strengthening.',
    rec_es: 'Reposo relativo, movimiento sin dolor, técnica de levantamiento, fortalecer el core.' },
  { slug: 'neck-strain', category: 'sports-injury', severity: 'mild', regions: ['cervical-spine'],
    name_ru: 'Растяжение мышц шеи', name_en: 'Neck strain', name_es: 'Distensión cervical',
    desc_ru: 'Перегрузка мышц и связок шеи от статичной позы, ударов или удержания положения.',
    desc_en: 'Overload of the neck muscles and ligaments from static posture, impacts or holding a position.',
    desc_es: 'Sobrecarga de los músculos y ligamentos del cuello por postura estática, impactos o mantener una posición.',
    imp_ru: 'Боль и скованность шеи, головная боль, ограничение поворотов головы.',
    imp_en: 'Neck pain and stiffness, headache, limited head rotation.',
    imp_es: 'Dolor y rigidez de cuello, dolor de cabeza, rotación limitada.',
    rec_ru: 'Мягкая мобилизация, коррекция осанки и эргономики, укрепление глубоких сгибателей шеи.',
    rec_en: 'Gentle mobilisation, posture and ergonomics, strengthen the deep neck flexors.',
    rec_es: 'Movilización suave, postura y ergonomía, fortalecer los flexores profundos del cuello.' },
  { slug: 'wrist-sprain', category: 'sports-injury', severity: 'mild', regions: [],
    name_ru: 'Растяжение связок запястья', name_en: 'Wrist sprain', name_es: 'Esguince de muñeca',
    desc_ru: 'Повреждение связок запястья при падении на вытянутую руку или переразгибании под весом.',
    desc_en: 'Injury to the wrist ligaments from a fall on an outstretched hand or overextension under load.',
    desc_es: 'Lesión de los ligamentos de la muñeca por caída con la mano extendida o hiperextensión bajo carga.',
    imp_ru: 'Боль, отёк и слабость хвата, боль при опоре на кисть.',
    imp_en: 'Pain, swelling and weak grip, pain when bearing weight on the hand.',
    imp_es: 'Dolor, hinchazón y agarre débil, dolor al apoyar la mano.',
    rec_ru: 'Покой и фиксация, постепенная нагрузка, укрепление предплечья; исключить перелом при сильной боли.',
    rec_en: 'Rest and support, gradual loading, forearm strengthening; rule out a fracture if pain is severe.',
    rec_es: 'Reposo y sujeción, carga gradual, fortalecer el antebrazo; descarte fractura si el dolor es intenso.' },
  { slug: 'boxers-fracture', category: 'sports-injury', severity: 'moderate', regions: [],
    name_ru: 'Перелом боксёра (пястной кости)', name_en: "Boxer's fracture (metacarpal)", name_es: 'Fractura del boxeador (metacarpiano)',
    desc_ru: 'Перелом шейки пятой пястной кости от удара сжатым кулаком.',
    desc_en: 'Fracture of the fifth metacarpal neck from a punch with a clenched fist.',
    desc_es: 'Fractura del cuello del quinto metacarpiano por un golpe con el puño cerrado.',
    imp_ru: 'Боль, отёк и деформация кисти у основания мизинца, слабость хвата.',
    imp_en: 'Pain, swelling and deformity of the hand at the base of the little finger, weak grip.',
    imp_es: 'Dolor, hinchazón y deformidad de la mano en la base del meñique, agarre débil.',
    rec_ru: 'Обследование и иммобилизация, иногда репозиция; правильная техника удара и бинтование.',
    rec_en: 'Evaluation and immobilisation, sometimes reduction; proper punch technique and wrapping.',
    rec_es: 'Evaluación e inmovilización, a veces reducción; técnica de golpe correcta y vendaje.' },
  { slug: 'hamstring-strain', category: 'sports-injury', severity: 'moderate', regions: [],
    name_ru: 'Растяжение задней поверхности бедра', name_en: 'Hamstring strain', name_es: 'Distensión de isquiotibiales',
    desc_ru: 'Надрыв мышц задней поверхности бедра при спринте или резком выпаде без разминки.',
    desc_en: 'Tear of the hamstring muscles during a sprint or sudden lunge without a warm-up.',
    desc_es: 'Desgarro de los isquiotibiales durante un esprint o una zancada brusca sin calentamiento.',
    imp_ru: 'Резкая боль сзади бедра, синяк, слабость при сгибании колена и беге.',
    imp_en: 'Sharp pain at the back of the thigh, bruising, weakness bending the knee and running.',
    imp_es: 'Dolor agudo en la parte posterior del muslo, hematoma, debilidad al flexionar la rodilla y correr.',
    rec_ru: 'Покой-лёд, затем эксцентрика на бицепс бедра, разминка и постепенный возврат к спринту.',
    rec_en: 'Rest-ice, then eccentric hamstring work, warm-ups and a gradual return to sprinting.',
    rec_es: 'Reposo-hielo, luego trabajo excéntrico, calentamiento y retorno gradual al esprint.' },
  { slug: 'shoulder-dislocation', category: 'sports-injury', severity: 'severe', regions: [],
    name_ru: 'Вывих плеча', name_en: 'Shoulder dislocation', name_es: 'Luxación de hombro',
    desc_ru: 'Смещение головки плечевой кости из суставной впадины при рычаге или падении.',
    desc_en: 'Displacement of the humeral head out of the socket from a lever force or fall.',
    desc_es: 'Desplazamiento de la cabeza del húmero fuera de la cavidad por palanca o caída.',
    imp_ru: 'Сильная боль, видимая деформация, невозможность двигать рукой; риск повторных вывихов.',
    imp_en: 'Severe pain, visible deformity, inability to move the arm; risk of recurrent dislocation.',
    imp_es: 'Dolor intenso, deformidad visible, incapacidad de mover el brazo; riesgo de recidiva.',
    rec_ru: 'Немедленное вправление врачом, иммобилизация, реабилитация; при рецидивах — операция.',
    rec_en: 'Prompt reduction by a clinician, immobilisation, rehab; surgery for recurrent cases.',
    rec_es: 'Reducción inmediata por un médico, inmovilización, rehabilitación; cirugía si es recurrente.' },
  { slug: 'stress-fracture', category: 'sports-injury', severity: 'moderate', regions: [],
    name_ru: 'Стресс-перелом', name_en: 'Stress fracture', name_es: 'Fractura por estrés',
    desc_ru: 'Микротрещина кости от повторной ударной нагрузки, превышающей скорость восстановления.',
    desc_en: 'A bone micro-crack from repetitive impact load that outpaces recovery.',
    desc_es: 'Microfisura ósea por carga de impacto repetida que supera la recuperación.',
    imp_ru: 'Локальная боль, нарастающая при нагрузке и стихающая в покое; чаще стопа и голень.',
    imp_en: 'Localised pain that builds with activity and eases at rest; commonly foot and shin.',
    imp_es: 'Dolor localizado que aumenta con la actividad y cede en reposo; frecuente en pie y espinilla.',
    rec_ru: 'Разгрузка и покой, постепенное возвращение, питание и витамин D/кальций, коррекция объёма.',
    rec_en: 'Offload and rest, gradual return, nutrition and vitamin D/calcium, correct training volume.',
    rec_es: 'Descargar y descansar, retorno gradual, nutrición y vitamina D/calcio, corregir el volumen.' },
  { slug: 'detached-retina', category: 'sports-injury', severity: 'severe', regions: [],
    name_ru: 'Отслойка сетчатки', name_en: 'Retinal detachment', name_es: 'Desprendimiento de retina',
    desc_ru: 'Отслоение сетчатки от задней стенки глаза, иногда после сильного удара в область глаза (бокс).',
    desc_en: 'Separation of the retina from the back of the eye, sometimes after a hard blow to the eye (boxing).',
    desc_es: 'Separación de la retina de la pared posterior del ojo, a veces tras un golpe fuerte (boxeo).',
    imp_ru: 'Вспышки, «занавес» или плавающие точки в поле зрения, внезапная потеря зрения — неотложное состояние.',
    imp_en: 'Flashes, a curtain or floaters in the visual field, sudden vision loss — a medical emergency.',
    imp_es: 'Destellos, una cortina o moscas volantes, pérdida súbita de visión — una urgencia médica.',
    rec_ru: 'Немедленно к офтальмологу — часто требуется срочная операция; защита глаз в контактном спорте.',
    rec_en: 'See an ophthalmologist immediately — often urgent surgery; eye protection in contact sport.',
    rec_es: 'Acuda al oftalmólogo de inmediato — a menudo cirugía urgente; protección ocular en deportes de contacto.' }
];

// Sport slug → the diagnosis slugs of its characteristic injuries. Mix of the new
// INJURY_CONDITIONS above and existing human_conditions rows (disc-herniation).
const SPORT_INJURIES = {
  'running':       ['runners-knee','itb-syndrome','plantar-fasciitis','achilles-tendinopathy','shin-splints','stress-fracture'],
  'walking':       ['plantar-fasciitis'],
  'swimming':      ['swimmers-shoulder','rotator-cuff-tear','neck-strain'],
  'cycling':       ['runners-knee','lumbar-strain','neck-strain','wrist-sprain'],
  'rowing':        ['lumbar-strain','disc-herniation','rotator-cuff-tear'],
  'tennis':        ['tennis-elbow','rotator-cuff-tear','ankle-sprain','lumbar-strain'],
  'basketball':    ['ankle-sprain','acl-tear','achilles-tendinopathy','runners-knee'],
  'football':      ['concussion','acl-tear','meniscus-tear','ankle-sprain','hamstring-strain'],
  'boxing':        ['concussion','cte','boxers-fracture','detached-retina','rotator-cuff-tear'],
  'wrestling':     ['shoulder-dislocation','neck-strain','acl-tear'],
  'martial-arts':  ['concussion','acl-tear','ankle-sprain','wrist-sprain','boxers-fracture'],
  'weightlifting': ['lumbar-strain','disc-herniation','rotator-cuff-tear','meniscus-tear'],
  'yoga':          ['hamstring-strain','wrist-sprain','lumbar-strain'],
  'pilates':       ['neck-strain','lumbar-strain'],
  'dance':         ['ankle-sprain','achilles-tendinopathy','stress-fracture'],
  'chess':         ['neck-strain','lumbar-strain']
};

module.exports = { SPORTS, SPORT_DIAG_LINKS, INJURY_CONDITIONS, SPORT_INJURIES };
